const DEFAULT_SPAWN_RING_RADIUS = 18;
const DEFAULT_CANDIDATE_LIMIT = 96;
const DEFAULT_MIN_CAPITAL_DISTANCE = 21;
const DEFAULT_TUTORIAL_RADIUS = 4;
const DEFAULT_TUTORIAL_TARGET_MIN_DISTANCE = 1;
const DEFAULT_TUTORIAL_TARGET_MAX_DISTANCE = 4;

module.exports = {
  DEFAULT_CANDIDATE_LIMIT,
  DEFAULT_MIN_CAPITAL_DISTANCE,
  DEFAULT_SPAWN_RING_RADIUS,
  DEFAULT_TUTORIAL_RADIUS,
  DEFAULT_TUTORIAL_TARGET_MAX_DISTANCE,
  DEFAULT_TUTORIAL_TARGET_MIN_DISTANCE,
};
