'use strict';

const { sourceRef } = require('./source-utils');

const TODAY = '2026-07-10';

function retired(task, gate, fireProbe, refs, contracts) {
  return {
    classification: 'retired-step4',
    retiredByTask: task,
    retirementEvidenceRefs: refs,
    blockingGate: gate,
    fireProbe,
    date: TODAY,
    contracts,
  };
}

function uiLocal(actionType, reason, refs, proof, growthPreventionTest) {
  return {
    classification: 'classified-ui-local',
    actionType,
    reason,
    evidenceRefs: refs,
    proofNotClientCommandSender: proof,
    owner: 'frontend/platform',
    growthPreventionTest,
  };
}

const DEBT_ITEMS = Object.freeze([
  {
    debtId: 'STEP4-DEBT-001',
    inventoryId: 'server:player-login',
    classification: 'legacy-route-orchestration-visible',
    currentStatus: 'permanent-exception',
    targetPhase: 1,
    contracts: ['COP-ROUTE-001', 'COP-ENTRY-001', 'COP-PROJECTION-001'],
    owner: 'auth/platform',
    reason: 'Login is an auth/player-state creation boundary, not a migrated gameplay command.',
    retirementCondition: 'If login becomes gameplay command traffic or mutates shared gameplay state, migrate it through CommandExecutionPipeline and the Step3/Step4 blocking maps.',
    growthPreventionTest: 'scripts/check-route-owned-persistence.test.js',
    sourceRefs: [
      sourceRef('backend/routes/playerRoutes.js', 61, 85, 'login route owns withPlayerStateLock + authService.loginPlayer callbacks + repository.save', 'server:player-login'),
      sourceRef('backend/routes/playerRoutes.js', 108, 148, 'POST /api/player/login projection response assembly', 'server:player-login'),
      sourceRef('scripts/command-owner-step1/inventories.js', 171, 189, 'SERVER_WRITE_ENTRIES server:player-login', 'server:player-login'),
      sourceRef('scripts/command-owner-step1/inventories.js', 802, 808, 'ROUTE_ORCHESTRATION_DEBT server:player-login', 'server:player-login'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 793, 795, 'Final Self-Audit remaining non-blocking debt server:player-login', 'server:player-login'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-002',
    inventoryId: 'admin:config-release-publish',
    classification: 'legacy-route-orchestration-visible',
    currentStatus: 'permanent-exception',
    targetPhase: 1,
    contracts: ['COP-ROUTE-001', 'COP-ENTRY-001'],
    owner: 'admin/config',
    reason: 'Config release publish is an admin/config write delegated to ConfigReleaseService, not gameplay state.',
    retirementCondition: 'If config release operations become gameplay command traffic, migrate through CommandExecutionPipeline and blocking maps.',
    growthPreventionTest: 'scripts/check-route-owned-persistence.test.js',
    sourceRefs: [
      sourceRef('backend/routes/adminRoutes.js', 83, 91, 'POST /api/admin/config-releases/publish delegates to ConfigReleaseService.publishRelease', 'admin:config-release-publish'),
      sourceRef('scripts/command-owner-step1/inventories.js', 299, 314, 'SERVER_WRITE_ENTRIES admin:config-release-publish', 'admin:config-release-publish'),
      sourceRef('scripts/command-owner-step1/inventories.js', 803, 808, 'ROUTE_ORCHESTRATION_DEBT admin:config-release-publish', 'admin:config-release-publish'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 799, 801, 'Final Self-Audit remaining non-blocking debt admin config release', 'admin:config-release-publish'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-003',
    inventoryId: 'admin:config-release-rollback',
    classification: 'legacy-route-orchestration-visible',
    currentStatus: 'permanent-exception',
    targetPhase: 1,
    contracts: ['COP-ROUTE-001', 'COP-ENTRY-001'],
    owner: 'admin/config',
    reason: 'Config release rollback is an admin/config write delegated to ConfigReleaseService, not gameplay state.',
    retirementCondition: 'If config release operations become gameplay command traffic, migrate through CommandExecutionPipeline and blocking maps.',
    growthPreventionTest: 'scripts/check-route-owned-persistence.test.js',
    sourceRefs: [
      sourceRef('backend/routes/adminRoutes.js', 94, 102, 'POST /api/admin/config-releases/rollback delegates to ConfigReleaseService.rollbackRelease', 'admin:config-release-rollback'),
      sourceRef('scripts/command-owner-step1/inventories.js', 315, 330, 'SERVER_WRITE_ENTRIES admin:config-release-rollback', 'admin:config-release-rollback'),
      sourceRef('scripts/command-owner-step1/inventories.js', 804, 808, 'ROUTE_ORCHESTRATION_DEBT admin:config-release-rollback', 'admin:config-release-rollback'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 799, 801, 'Final Self-Audit remaining non-blocking debt admin config release', 'admin:config-release-rollback'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-004',
    inventoryId: 'admin:ops-login-audit',
    classification: 'classified-non-gameplay-ops-command',
    currentStatus: 'permanent-exception',
    targetPhase: 1,
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001', 'COP-IDEMP-001'],
    owner: 'ops/platform',
    reason: 'Ops login audit appends operational audit records outside gameplay state.',
    retirementCondition: 'If it mutates gameplay state or claims gameplay migration, add owner/idempotency/pipeline/tests/blocking-map entries.',
    growthPreventionTest: 'scripts/check-permanent-exceptions.test.js',
    sourceRefs: [
      sourceRef('backend/routes/opsRoutes.js', 23, 32, 'ops login route command entry / audit path', 'admin:ops-login-audit'),
      sourceRef('scripts/command-owner-step1/inventories.js', 213, 230, 'SERVER_WRITE_ENTRIES admin:ops-login-audit', 'admin:ops-login-audit'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 796, 798, 'Final Self-Audit remaining non-blocking debt ops writes', 'admin:ops-login-audit'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-005',
    inventoryId: 'admin:ops-maintenance-state',
    classification: 'classified-non-gameplay-ops-command',
    currentStatus: 'permanent-exception',
    targetPhase: 1,
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001', 'COP-IDEMP-001'],
    owner: 'ops/platform',
    reason: 'Maintenance state is an ops control file write plus audit append, outside gameplay state.',
    retirementCondition: 'If it mutates gameplay state or claims gameplay migration, add owner/idempotency/pipeline/tests/blocking-map entries.',
    growthPreventionTest: 'scripts/check-permanent-exceptions.test.js',
    sourceRefs: [
      sourceRef('backend/routes/opsRoutes.js', 68, 78, 'ops maintenance route delegates to OpsControlService.setMaintenanceState', 'admin:ops-maintenance-state'),
      sourceRef('scripts/command-owner-step1/inventories.js', 231, 248, 'SERVER_WRITE_ENTRIES admin:ops-maintenance-state', 'admin:ops-maintenance-state'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 796, 798, 'Final Self-Audit remaining non-blocking debt ops writes', 'admin:ops-maintenance-state'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-006',
    inventoryId: 'admin:ops-restart-audit',
    classification: 'classified-non-gameplay-ops-command',
    currentStatus: 'permanent-exception',
    targetPhase: 1,
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001', 'COP-IDEMP-001'],
    owner: 'ops/platform',
    reason: 'Restart writes ops audit/process-control state outside gameplay state.',
    retirementCondition: 'If it mutates gameplay state or claims gameplay migration, add owner/idempotency/pipeline/tests/blocking-map entries.',
    growthPreventionTest: 'scripts/check-permanent-exceptions.test.js',
    sourceRefs: [
      sourceRef('backend/routes/opsRoutes.js', 86, 118, 'ops restart route delegates to OpsControlService.restartService / audit', 'admin:ops-restart-audit'),
      sourceRef('scripts/command-owner-step1/inventories.js', 249, 266, 'SERVER_WRITE_ENTRIES admin:ops-restart-audit', 'admin:ops-restart-audit'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 796, 798, 'Final Self-Audit remaining non-blocking debt ops writes', 'admin:ops-restart-audit'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-007',
    inventoryId: 'diagnostic:client-events-ingest',
    classification: 'diagnostic-classified',
    currentStatus: 'permanent-exception',
    targetPhase: 1,
    contracts: ['COP-ENTRY-001', 'COP-TRACE-001'],
    owner: 'observability',
    reason: 'Client event ingestion writes diagnostic observability data only.',
    retirementCondition: 'If diagnostic ingestion affects gameplay state, add command ownership and blocking migration.',
    growthPreventionTest: 'scripts/check-permanent-exceptions.test.js',
    sourceRefs: [
      sourceRef('backend/routes/clientEventsRoutes.js', 40, 58, 'POST /api/client-events diagnostic ingestion', 'diagnostic:client-events-ingest'),
      sourceRef('scripts/command-owner-step1/inventories.js', 267, 282, 'SERVER_WRITE_ENTRIES diagnostic:client-events-ingest', 'diagnostic:client-events-ingest'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 802, 804, 'Final Self-Audit remaining non-blocking debt diagnostic writes', 'diagnostic:client-events-ingest'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-008',
    inventoryId: 'diagnostic:client-operation-log-ingest',
    classification: 'diagnostic-classified',
    currentStatus: 'permanent-exception',
    targetPhase: 1,
    contracts: ['COP-ENTRY-001', 'COP-TRACE-001', 'COP-CLIENT-001'],
    owner: 'observability',
    reason: 'Client operation log ingestion writes diagnostic log rows only.',
    retirementCondition: 'If diagnostic ingestion affects gameplay state, add command ownership and blocking migration.',
    growthPreventionTest: 'scripts/check-permanent-exceptions.test.js',
    sourceRefs: [
      sourceRef('backend/routes/clientEventsRoutes.js', 73, 95, 'POST /api/client-operation-logs diagnostic ingestion', 'diagnostic:client-operation-log-ingest'),
      sourceRef('scripts/command-owner-step1/inventories.js', 283, 298, 'SERVER_WRITE_ENTRIES diagnostic:client-operation-log-ingest', 'diagnostic:client-operation-log-ingest'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 802, 804, 'Final Self-Audit remaining non-blocking debt diagnostic writes', 'diagnostic:client-operation-log-ingest'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-009',
    inventoryId: 'frontend:canvas-action-dispatcher-disabled-drop',
    classification: 'domain-blocker',
    currentStatus: 'retired',
    targetPhase: 4,
    contracts: ['COP-CLIENT-001', 'COP-CLIENT-002', 'COP-ALLOWLIST-001'],
    sourceRefs: [
      sourceRef('frontend/js/platform/CanvasActionDispatcher.js', 105, 129, 'CanvasActionDispatcher.handle calls ClientCommandSemantics.normalizeAction before disabled check and dispatch', 'frontend:canvas-action-dispatcher-disabled-drop'),
      sourceRef('scripts/command-owner-step1/inventories.js', 571, 588, 'FRONTEND_COMMAND_PATHS retired-step4 entry', 'frontend:canvas-action-dispatcher-disabled-drop'),
      sourceRef('scripts/command-owner-step1/inventories.js', 642, 657, 'CLIENT_LOCAL_BLOCKS retired-step4 entry', 'frontend:canvas-action-dispatcher-disabled-drop'),
    ],
    inventoryDrift: {
      status: 'resolved-step4',
      currentSourceFact: 'Command action disabled is converted to visualDisabled by normalizeAction before dispatcher disabled check.',
      updateTask: 'STEP4-T21',
    },
    retiredStep4: retired(
      'STEP4-T11',
      'scripts/check-frontend-command-semantics.js',
      'Remove normalizeAction or reintroduce command disabled early-return -> exit 1',
      [sourceRef('frontend/js/platform/CanvasActionDispatcher.js', 105, 129, 'normalizeAction before disabled gate', 'frontend:canvas-action-dispatcher-disabled-drop')],
      ['COP-CLIENT-001', 'COP-CLIENT-002'],
    ),
  },
  {
    debtId: 'STEP4-DEBT-010',
    inventoryId: 'frontend:canvas-panel-action-runner-disabled-drop',
    classification: 'domain-blocker',
    currentStatus: 'classified-ui-local',
    targetPhase: 4,
    contracts: ['COP-CLIENT-001', 'COP-CLIENT-002', 'COP-ALLOWLIST-001'],
    sourceRefs: [
      sourceRef('frontend/js/platform/CanvasPanelActionRunner.js', 160, 178, 'CanvasPanelActionRunner.run UI-local disabled guard before panel descriptor execution', 'frontend:canvas-panel-action-runner-disabled-drop'),
      sourceRef('frontend/js/platform/CanvasPanelActionRegistry.js', 8, 70, 'CanvasPanelActionRegistry built-in descriptors are panel open/close/action UI operations only', 'frontend:canvas-panel-action-runner-disabled-drop'),
      sourceRef('scripts/command-owner-step1/inventories.js', 589, 606, 'FRONTEND_COMMAND_PATHS classified-ui-local panel entry', 'frontend:canvas-panel-action-runner-disabled-drop'),
      sourceRef('scripts/command-owner-step1/inventories.js', 659, 675, 'CLIENT_LOCAL_BLOCKS classified-ui-local panel entry', 'frontend:canvas-panel-action-runner-disabled-drop'),
    ],
    inventoryDrift: {
      status: 'resolved-step4',
      currentSourceFact: 'Production panel descriptors are UI-local and do not submit ClientCommandSender commands; no production CanvasPanelActionRegistry.register call exists.',
      updateTask: 'STEP4-T21',
    },
    classifiedUiLocal: uiLocal(
      'openFamousPersons|closeFamousPersons|changeFamousPersonsPage|openFamousPersonDetail|closeFamousPersonDetail|showFamousSkillTooltip|clearFamousSkillTooltip|panelOutsideClick',
      'Panel actions only open/close/run UI panel surface descriptors and do not submit commands.',
      [
        sourceRef('frontend/js/platform/CanvasPanelActionRunner.js', 135, 156, 'executeDescriptor calls panel surface manager only', 'frontend:canvas-panel-action-runner-disabled-drop'),
        sourceRef('frontend/js/platform/CanvasPanelActionRegistry.js', 8, 70, 'built-in panel descriptors', 'frontend:canvas-panel-action-runner-disabled-drop'),
      ],
      'CanvasPanelActionRegistry production descriptors resolve to panel surface operations; rg found no production CanvasPanelActionRegistry.register call.',
      'scripts/check-frontend-command-semantics.test.js',
    ),
  },
  {
    debtId: 'STEP4-DEBT-011',
    inventoryId: 'frontend:canvas-game-app-advance-era-local-block',
    classification: 'domain-blocker',
    currentStatus: 'retired',
    targetPhase: 4,
    contracts: ['COP-CLIENT-001', 'COP-AUTHORITY-001', 'COP-TIME-001'],
    sourceRefs: [
      sourceRef('frontend/js/platform/CanvasGameApp.js', 1224, 1232, 'canAdvanceEraNow builds visual civilization view state only', 'frontend:canvas-game-app-advance-era-local-block'),
      sourceRef('frontend/js/platform/CanvasGameApp.js', 2819, 2833, 'advanceEra directly calls GameAPI.advanceEra without canAdvanceEraNow guard', 'frontend:canvas-game-app-advance-era-local-block'),
      sourceRef('scripts/command-owner-step1/inventories.js', 608, 625, 'FRONTEND_COMMAND_PATHS retired-step4 advanceEra entry', 'frontend:canvas-game-app-advance-era-local-block'),
      sourceRef('scripts/command-owner-step1/inventories.js', 677, 692, 'CLIENT_LOCAL_BLOCKS retired-step4 advanceEra entry', 'frontend:canvas-game-app-advance-era-local-block'),
    ],
    inventoryDrift: {
      status: 'resolved-step4',
      currentSourceFact: 'CanvasGameApp.advanceEra already calls GameAPI.advanceEra directly; canAdvanceEraNow remains visual-state only.',
      updateTask: 'STEP4-T21',
    },
    retiredStep4: retired(
      'STEP4-T13',
      'scripts/check-frontend-command-semantics.js',
      'Reintroduce if (!this.canAdvanceEraNow()) return false before GameAPI.advanceEra -> exit 1',
      [sourceRef('frontend/js/platform/CanvasGameApp.js', 2819, 2833, 'advanceEra direct GameAPI call', 'frontend:canvas-game-app-advance-era-local-block')],
      ['COP-CLIENT-001', 'COP-AUTHORITY-001', 'COP-TIME-001'],
    ),
  },
  {
    debtId: 'STEP4-DEBT-012',
    inventoryId: 'frontend:tech-research-local-canresearch',
    classification: 'domain-blocker',
    currentStatus: 'retired',
    targetPhase: 4,
    contracts: ['COP-CLIENT-001'],
    sourceRefs: [
      sourceRef('frontend/js/platform/GameCommandService.js', 1, 80, 'GameCommandService research command path delegates to GameAPI through ClientCommandSender-backed helper', 'frontend:tech-research-local-canresearch'),
      sourceRef('frontend/js/platform/CanvasActionController.js', 417, 560, 'CanvasActionController action routing does not treat canResearch as a command-submit early return', 'frontend:tech-research-local-canresearch'),
      sourceRef('scripts/command-owner-step1/inventories.js', 694, 709, 'CLIENT_LOCAL_BLOCKS tech-research-local-canresearch', 'frontend:tech-research-local-canresearch'),
    ],
    retiredStep4: retired(
      'STEP4-T14',
      'scripts/check-frontend-command-semantics.js',
      'Add canResearch/disabled domain early return on command-submit path -> exit 1',
      [sourceRef('frontend/js/platform/GameCommandService.js', 1, 80, 'research submit path', 'frontend:tech-research-local-canresearch')],
      ['COP-CLIENT-001'],
    ),
  },
  {
    debtId: 'STEP4-DEBT-013',
    inventoryId: 'frontend:building-local-cost-disabled',
    classification: 'domain-blocker',
    currentStatus: 'retired',
    targetPhase: 4,
    contracts: ['COP-CLIENT-001'],
    sourceRefs: [
      sourceRef('frontend/js/platform/CanvasActionDescriptorRegistry.js', 12, 32, 'building build/upgrade descriptors declare command-submit payload and trace fields', 'frontend:building-local-cost-disabled'),
      sourceRef('frontend/js/platform/GameCommandService.js', 97, 128, 'GameCommandService build/upgrade command path delegates to GameAPI through ClientCommandSender-backed helper', 'frontend:building-local-cost-disabled'),
      sourceRef('scripts/command-owner-step1/inventories.js', 711, 726, 'CLIENT_LOCAL_BLOCKS building-local-cost-disabled', 'frontend:building-local-cost-disabled'),
    ],
    retiredStep4: retired(
      'STEP4-T14',
      'scripts/check-frontend-command-semantics.js',
      'Add cost/unlocked/maxLevel disabled early return on command-submit path -> exit 1',
      [sourceRef('frontend/js/platform/GameCommandService.js', 97, 128, 'building submit path', 'frontend:building-local-cost-disabled')],
      ['COP-CLIENT-001'],
    ),
  },
  {
    debtId: 'STEP4-DEBT-014',
    inventoryId: 'frontend:famous-candidate-availability',
    classification: 'domain-blocker',
    currentStatus: 'retired',
    targetPhase: 4,
    contracts: ['COP-CLIENT-001'],
    sourceRefs: [
      sourceRef('frontend/js/platform/CanvasActionController.js', 417, 560, 'CanvasActionController routes famous command actions without candidate availability early return in dispatcher path', 'frontend:famous-candidate-availability'),
      sourceRef('frontend/js/api/GameAPI.js', 746, 760, 'GameAPI accept/dismiss famous candidate command helpers submit commands', 'frontend:famous-candidate-availability'),
      sourceRef('scripts/command-owner-step1/inventories.js', 728, 743, 'CLIENT_LOCAL_BLOCKS famous-candidate-availability', 'frontend:famous-candidate-availability'),
    ],
    retiredStep4: retired(
      'STEP4-T14',
      'scripts/check-frontend-command-semantics.js',
      'Add candidate availability early return on command-submit path -> exit 1',
      [sourceRef('frontend/js/api/GameAPI.js', 746, 760, 'famous command helpers', 'frontend:famous-candidate-availability')],
      ['COP-CLIENT-001'],
    ),
  },
  {
    debtId: 'STEP4-DEBT-015',
    inventoryId: 'frontend:territory-mission-ready',
    classification: 'domain-blocker',
    currentStatus: 'retired',
    targetPhase: 4,
    contracts: ['COP-OWNER-002'],
    sourceRefs: [
      sourceRef('frontend/js/platform/CanvasActionController.js', 510, 515, 'territoryAction/claimConquest routing is action dispatch only', 'frontend:territory-mission-ready'),
      sourceRef('frontend/js/api/GameAPI.js', 880, 886, 'GameAPI claimConquest submits command', 'frontend:territory-mission-ready'),
      sourceRef('scripts/command-owner-step1/inventories.js', 745, 760, 'CLIENT_LOCAL_BLOCKS territory-mission-ready', 'frontend:territory-mission-ready'),
    ],
    retiredStep4: retired(
      'STEP4-T14',
      'scripts/check-frontend-command-semantics.js',
      'Add claimable/ready early return on command-submit path -> exit 1',
      [sourceRef('frontend/js/api/GameAPI.js', 880, 886, 'claimConquest helper', 'frontend:territory-mission-ready')],
      ['COP-OWNER-002'],
    ),
  },
  {
    debtId: 'STEP4-DEBT-016',
    inventoryId: 'frontend:world-march-passability',
    classification: 'domain-blocker',
    currentStatus: 'retired',
    targetPhase: 4,
    contracts: ['COP-TIME-001'],
    sourceRefs: [
      sourceRef('frontend/js/platform/CanvasActionController.js', 442, 442, 'confirmWorldMarchDeployment routes after warning confirmation', 'frontend:world-march-passability'),
      sourceRef('frontend/js/api/GameAPI.js', 821, 829, 'GameAPI startWorldMarch submits command', 'frontend:world-march-passability'),
      sourceRef('scripts/command-owner-step1/inventories.js', 762, 777, 'CLIENT_LOCAL_BLOCKS world-march-passability', 'frontend:world-march-passability'),
    ],
    retiredStep4: retired(
      'STEP4-T14',
      'scripts/check-frontend-command-semantics.js',
      'Add passability/busy early return on command-submit path -> exit 1',
      [sourceRef('frontend/js/api/GameAPI.js', 821, 829, 'startWorldMarch helper', 'frontend:world-march-passability')],
      ['COP-TIME-001'],
    ),
  },
  {
    debtId: 'STEP4-DEBT-017',
    inventoryId: 'COP-OWNER-002: resolveCapture',
    classification: 'phase7-remaining-debt',
    currentStatus: 'remaining-explicit',
    targetPhase: 7,
    contracts: ['COP-OWNER-002'],
    owner: 'territory/world',
    reason: 'resolveCapture remains private player-owned in current scope.',
    retirementCondition: 'If future scope makes capture decisions shared, migrate owner resolution to shared owner keys and add blocking evidence.',
    growthPreventionTest: 'scripts/check-step4-final-audit.test.js',
    sourceRefs: [
      sourceRef('frontend/js/api/GameAPI.js', 813, 819, 'resolveCapture client helper remains a command helper but owner scope is private player-owned', 'COP-OWNER-002: resolveCapture'),
      sourceRef('backend/application/commands/CommandOwnerResolver.js', 20, 22, 'resolveCapture owner declaration', 'COP-OWNER-002: resolveCapture'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 777, 777, 'Final implementation handoff remaining debt COP-OWNER-002 resolveCapture', 'COP-OWNER-002: resolveCapture'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-018',
    inventoryId: 'COP-SHARED-001: loot/boss',
    classification: 'phase7-remaining-debt',
    currentStatus: 'remaining-explicit',
    targetPhase: 7,
    contracts: ['COP-SHARED-001'],
    owner: 'shared-world',
    reason: 'Loot/boss shared owners are future abstractions only; no current routes exist in Step4 scope.',
    retirementCondition: 'When loot/boss routes exist, add shared owner declarations, locks, route migration, tests, and blocking-map entries.',
    growthPreventionTest: 'scripts/check-step4-final-audit.test.js',
    sourceRefs: [
      sourceRef('backend/application/commands/CommandOwnerResolver.js', 5, 32, 'resolveCapture current player command declarations; no loot/boss route declaration in Step4 scope', 'COP-SHARED-001: loot/boss'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 778, 778, 'Final implementation handoff remaining debt COP-SHARED-001 loot/boss', 'COP-SHARED-001: loot/boss'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-019',
    inventoryId: 'COP-CLIENT-001/002: report-only findings',
    classification: 'phase7-remaining-debt',
    currentStatus: 'partially-retired',
    targetPhase: 4,
    contracts: ['COP-CLIENT-001', 'COP-CLIENT-002'],
    owner: 'frontend',
    reason: 'Step4 retires command-submit blockers while broad renderer/panel architecture reports remain visible backlog.',
    retirementCondition: 'Retire remaining frontend report-only findings only after structural code removal plus blocking gates and FIRE probes.',
    growthPreventionTest: 'scripts/check-frontend-command-semantics.test.js',
    sourceRefs: [
      sourceRef('scripts/report-frontend-ecs-input-branch.js', 226, 246, 'frontend ECS input branch report-only scanner', 'COP-CLIENT-001/002: report-only findings'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 783, 786, 'Final implementation handoff remaining debt COP-CLIENT frontend reports', 'COP-CLIENT-001/002: report-only findings'),
    ],
  },
  {
    debtId: 'STEP4-DEBT-020',
    inventoryId: 'COP-PROJECTION-001: domain business candidates',
    classification: 'phase7-remaining-debt',
    currentStatus: 'partially-retired',
    targetPhase: 5,
    contracts: ['COP-PROJECTION-001'],
    owner: 'architecture',
    reason: 'Broad domain-business candidate report remains architecture backlog; Step4 extracts command-owner/projection-overlap checks into focused blocking gates.',
    retirementCondition: 'Retire only focused sub-findings whose underlying projection/write coupling has been structurally removed and blocked.',
    growthPreventionTest: 'scripts/check-projection-write-boundary.test.js',
    sourceRefs: [
      sourceRef('scripts/report-domain-business-candidates.js', 421, 440, 'domain business candidate report-only scanner', 'COP-PROJECTION-001: domain business candidates'),
      sourceRef('docs/architecture/step3-phase2-7-verification-2026-07-10.md', 787, 787, 'Final implementation handoff remaining debt COP-PROJECTION-001', 'COP-PROJECTION-001: domain business candidates'),
    ],
  },
]);

module.exports = {
  DEBT_ITEMS,
  TODAY,
};
