'use strict';

function entry(data) {
  return Object.freeze({
    idempotencyClassification: 'non-idempotent',
    migrationPhase: 'pipeline-pending',
    contracts: ['COP-ENTRY-001'],
    evidence: [],
    notes: '',
    ...data,
  });
}

const SERVER_WRITE_ENTRIES = Object.freeze([
  entry({
    inventoryId: 'server:game-action-build-handler',
    route: '/api/game/action',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'build',
    provisionalOwnerKey: 'player:{playerId}',
    targetIdFields: ['target', 'buildingId'],
    currentExecutor: 'BuildBuildingCommandHandler',
    currentLockOwner: 'handler:repository.withPlayerStateLock',
    currentPersistenceOwner: 'handler:repository.save',
    currentProjectionOwner: 'handler:GameActionProjection.buildGameActionView',
    idempotencyClassification: 'server-fallback-id',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-HANDLER-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/gameRoutes.js', 'backend/application/commands/BuildBuildingCommandHandler.js'],
    notes: 'Build is special-cased into the command handler, but the handler still owns lock, load, save, and projection.',
  }),
  entry({
    inventoryId: 'server:game-action-registry',
    route: '/api/game/action',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'registry-actions',
    provisionalOwnerKey: 'mixed-see-game-action-inventory',
    targetIdFields: ['action-specific'],
    currentExecutor: 'GameActionRegistry.execute',
    currentLockOwner: 'route:withPlayerStateLock',
    currentPersistenceOwner: 'route:repository.save',
    currentProjectionOwner: 'route:buildGameView',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-OWNER-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/gameRoutes.js', 'backend/actions/GameActionRegistry.js'],
    notes: 'Route performs load, tutorial sync, validation, registry execution, save, retry, and projection.',
  }),
  entry({
    inventoryId: 'server:game-action-world-combat-bypass',
    route: '/api/game/action',
    method: 'POST',
    writeEntryKind: 'shared-target-write',
    commandType: 'startWorldCombat|resolveWorldCombat',
    provisionalOwnerKey: 'encounter:{encounterId}',
    targetIdFields: ['encounterId', 'combatEncounterId', 'missionId', 'battleId'],
    currentExecutor: 'executeWorldCombatAction -> WorldCombatSessionService',
    currentLockOwner: 'route:withPlayerStateLock',
    currentPersistenceOwner: 'route:repository.save plus worldEncounterRepo.upsertEncounter',
    currentProjectionOwner: 'route:buildGameView',
    migrationPhase: 'owner-resolution-blocked',
    contracts: ['COP-ENTRY-001', 'COP-OWNER-002', 'COP-SHARED-001', 'COP-ROUTE-001'],
    evidence: ['backend/routes/gameRoutes.js', 'backend/services/worldCombat/WorldCombatSessionService.js'],
    notes: 'World combat bypasses GameActionRegistry and must prove encounter owner lookup before domain execution.',
  }),
  entry({
    inventoryId: 'server:game-tasks-claim',
    route: '/api/game/tasks/claim',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'claimTaskReward',
    provisionalOwnerKey: 'player:{playerId}',
    targetIdFields: ['taskId', 'category'],
    currentExecutor: 'TaskCenterService.claimTask',
    currentLockOwner: 'route:withPlayerStateLock',
    currentPersistenceOwner: 'route:repository.save',
    currentProjectionOwner: 'route:buildGameView',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/gameRoutes.js'],
  }),
  entry({
    inventoryId: 'server:game-heartbeat-march-settlement',
    route: '/api/game/heartbeat',
    method: 'GET|POST',
    writeEntryKind: 'player-write',
    commandType: 'heartbeatMarchSettlement',
    provisionalOwnerKey: 'player:{playerId}',
    targetIdFields: ['active exploreMissions due time'],
    currentExecutor: 'settleDueMarchesOnHeartbeat',
    currentLockOwner: 'route:withPlayerStateLock',
    currentPersistenceOwner: 'route:repository.save',
    currentProjectionOwner: 'none',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TIME-001'],
    evidence: ['backend/routes/gameRoutes.js'],
  }),
  entry({
    inventoryId: 'server:game-heartbeat-client-report',
    route: '/api/game/heartbeat',
    method: 'POST',
    writeEntryKind: 'diagnostic-write',
    commandType: 'worldMarchClientReportIngest',
    provisionalOwnerKey: 'diagnostic:{playerId}',
    targetIdFields: ['worldMarchClientReport.missions'],
    currentExecutor: 'recordWorldMarchClientReport',
    currentLockOwner: 'route:withPlayerStateLock',
    currentPersistenceOwner: 'route:repository.save',
    currentProjectionOwner: 'none',
    migrationPhase: 'diagnostic-classified',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001'],
    evidence: ['backend/routes/gameRoutes.js'],
  }),
  entry({
    inventoryId: 'server:buildings-build-legacy-route',
    route: '/api/buildings/build',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'build',
    provisionalOwnerKey: 'player:{playerId}',
    targetIdFields: ['buildingType'],
    currentExecutor: 'BuildingActionService.build',
    currentLockOwner: 'route:withPlayerStateLock',
    currentPersistenceOwner: 'route:repository.save',
    currentProjectionOwner: 'route:getClientGameStateFromNormalized',
    migrationPhase: 'legacy-route-debt',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/buildingRoutes.js'],
  }),
  entry({
    inventoryId: 'server:player-login',
    route: '/api/player/login',
    method: 'POST',
    writeEntryKind: 'auth-player-write',
    commandType: 'playerLogin',
    provisionalOwnerKey: 'player:{username}',
    targetIdFields: ['username'],
    currentExecutor: 'authService.loginPlayer',
    currentLockOwner: 'route:withPlayerStateLock(username)',
    currentPersistenceOwner: 'route callback:repository.save',
    currentProjectionOwner: 'route:getClientGameStateFromNormalized',
    migrationPhase: 'classified-non-gameplay-command',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-LOCK-001'],
    evidence: ['backend/routes/playerRoutes.js'],
  }),
  entry({
    inventoryId: 'server:player-reset',
    route: '/api/player/reset',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'playerReset',
    provisionalOwnerKey: 'player:{playerId}',
    targetIdFields: [],
    currentExecutor: 'authService.resetPlayer',
    currentLockOwner: 'route:withPlayerStateLock',
    currentPersistenceOwner: 'route callback:repository.save|repository.resetPlayerState',
    currentProjectionOwner: 'route:getClientGameStateFromNormalized',
    migrationPhase: 'classified-reset-write',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-LOCK-001'],
    evidence: ['backend/routes/playerRoutes.js'],
  }),
  entry({
    inventoryId: 'admin:ops-login-audit',
    route: '/api/admin/ops/login',
    method: 'POST',
    writeEntryKind: 'ops-audit-write',
    commandType: 'opsLoginAudit',
    provisionalOwnerKey: 'ops:global',
    targetIdFields: ['username', 'clientIp'],
    currentExecutor: 'OpsAuthService.login + OpsControlService.appendAudit',
    currentLockOwner: 'none',
    currentPersistenceOwner: 'OpsControlService.appendAudit -> fs.appendFileSync',
    currentProjectionOwner: 'route:ops login result',
    idempotencyClassification: 'audit-append-only-no-client-id',
    migrationPhase: 'classified-non-gameplay-ops-command',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/opsRoutes.js:23', 'backend/services/OpsControlService.js:237'],
    notes: 'Login success/failure/rate-limit attempts append ops audit records outside gameplay state.',
  }),
  entry({
    inventoryId: 'admin:ops-maintenance-state',
    route: '/api/admin/ops/maintenance',
    method: 'POST',
    writeEntryKind: 'ops-state-write',
    commandType: 'opsMaintenanceSet',
    provisionalOwnerKey: 'ops:global',
    targetIdFields: ['enabled', 'reason', 'message'],
    currentExecutor: 'OpsControlService.setMaintenanceState',
    currentLockOwner: 'filesystem-local',
    currentPersistenceOwner: 'writeJsonFile -> fs.writeFileSync plus OpsControlService.appendAudit',
    currentProjectionOwner: 'route:maintenance result',
    idempotencyClassification: 'last-write-wins-no-client-id',
    migrationPhase: 'classified-non-gameplay-ops-command',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/opsRoutes.js:64', 'backend/services/OpsControlService.js:64', 'backend/services/OpsControlService.js:207'],
    notes: 'Maintenance state is persisted to an ops JSON file and also appends an audit record.',
  }),
  entry({
    inventoryId: 'admin:ops-restart-audit',
    route: '/api/admin/ops/restart',
    method: 'POST',
    writeEntryKind: 'ops-audit-and-process-write',
    commandType: 'opsRestartAccepted',
    provisionalOwnerKey: 'ops:global',
    targetIdFields: ['delayMs'],
    currentExecutor: 'OpsControlService.appendAudit + OpsControlService.restartService',
    currentLockOwner: 'none',
    currentPersistenceOwner: 'OpsControlService.appendAudit -> fs.appendFileSync and pm2 process control',
    currentProjectionOwner: 'route:accepted restart result',
    idempotencyClassification: 'non-idempotent',
    migrationPhase: 'classified-non-gameplay-ops-command',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/opsRoutes.js:71', 'backend/services/OpsControlService.js:237', 'backend/services/OpsControlService.js:514'],
    notes: 'Restart requests append accepted/failed audit records and can trigger PM2 process restart.',
  }),
  entry({
    inventoryId: 'diagnostic:client-events-ingest',
    route: '/api/client-events',
    method: 'POST',
    writeEntryKind: 'diagnostic-write',
    commandType: 'clientEventIngest',
    provisionalOwnerKey: 'diagnostic:anonymous-or-client',
    targetIdFields: ['type'],
    currentExecutor: 'ObservabilityService.recordClientEvent',
    currentLockOwner: 'none',
    currentPersistenceOwner: 'observabilityService',
    currentProjectionOwner: 'route:accepted event summary',
    migrationPhase: 'diagnostic-classified',
    contracts: ['COP-ENTRY-001', 'COP-TRACE-001'],
    evidence: ['backend/routes/clientEventsRoutes.js'],
  }),
  entry({
    inventoryId: 'diagnostic:client-operation-log-ingest',
    route: '/api/client-operation-logs',
    method: 'POST',
    writeEntryKind: 'diagnostic-write',
    commandType: 'clientOperationLogIngest',
    provisionalOwnerKey: 'diagnostic:{playerId}',
    targetIdFields: ['requestId', 'entries'],
    currentExecutor: 'logService.logClientOperationSnapshot',
    currentLockOwner: 'none',
    currentPersistenceOwner: 'logService client_operation_logs table',
    currentProjectionOwner: 'route:accepted log summary',
    migrationPhase: 'diagnostic-classified',
    contracts: ['COP-ENTRY-001', 'COP-TRACE-001', 'COP-CLIENT-001'],
    evidence: ['backend/routes/clientEventsRoutes.js', 'backend/services/logService.js'],
  }),
  entry({
    inventoryId: 'admin:config-release-publish',
    route: '/api/admin/config-releases/publish',
    method: 'POST',
    writeEntryKind: 'config-write',
    commandType: 'configReleasePublish',
    provisionalOwnerKey: 'config:gameplay',
    targetIdFields: ['release payload'],
    currentExecutor: 'ConfigReleaseService.publishRelease',
    currentLockOwner: 'service-owned-or-filesystem',
    currentPersistenceOwner: 'ConfigReleaseService',
    currentProjectionOwner: 'route:release result',
    migrationPhase: 'config-write-classified',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001'],
    evidence: ['backend/routes/adminRoutes.js'],
  }),
  entry({
    inventoryId: 'admin:config-release-rollback',
    route: '/api/admin/config-releases/rollback',
    method: 'POST',
    writeEntryKind: 'config-write',
    commandType: 'configReleaseRollback',
    provisionalOwnerKey: 'config:gameplay',
    targetIdFields: ['releaseId'],
    currentExecutor: 'ConfigReleaseService.rollbackRelease',
    currentLockOwner: 'service-owned-or-filesystem',
    currentPersistenceOwner: 'ConfigReleaseService',
    currentProjectionOwner: 'route:release result',
    migrationPhase: 'config-write-classified',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001'],
    evidence: ['backend/routes/adminRoutes.js'],
  }),
  entry({
    inventoryId: 'worker:world-worker-runtime-writes',
    route: 'backend/world-worker.js',
    method: 'BACKGROUND',
    writeEntryKind: 'background-worker-write',
    commandType: 'worldWorkerRuntimeTick',
    provisionalOwnerKey: 'mixed-player-and-shared-world',
    targetIdFields: ['playerId', 'encounterId', 'territoryId'],
    currentExecutor: 'WorldWorkerService',
    currentLockOwner: 'worker/service-local',
    currentPersistenceOwner: 'repository.save and shared repositories',
    currentProjectionOwner: 'none',
    migrationPhase: 'worker-write-classified',
    contracts: ['COP-ENTRY-001', 'COP-SHARED-001', 'COP-LOCK-001'],
    evidence: ['backend/world-worker.js', 'backend/services/realtime/WorldWorkerService.js'],
  }),
]);

const GAME_ACTION_ROWS = Object.freeze([
  ['build', 'BuildBuildingAction or BuildBuildingCommandHandler', 'player:{playerId}', ['target', 'buildingId'], 'server-fallback-id', 'handler special case plus legacy route debt'],
  ['upgrade', 'BuildBuildingAction', 'player:{playerId}', ['target'], 'non-idempotent', 'registry action'],
  ['advanceEra', 'AdvanceEraAction', 'player:{playerId}', [], 'non-idempotent', 'frontend local domain blocker is visible debt'],
  ['claimEvent', 'ClaimEventAction', 'player:{playerId}', ['eventId', 'optionId'], 'non-idempotent', 'event target currently private'],
  ['assign', 'AssignPopulationAction', 'player:{playerId}', ['target', 'count'], 'non-idempotent', 'registry action'],
  ['tutorialAdvance', 'TutorialService.advanceClientStep', 'player:{playerId}', ['step'], 'non-idempotent', 'registry action'],
  ['claimTaskReward', 'TaskCenterService.claimTask', 'player:{playerId}', ['taskId', 'category'], 'non-idempotent', 'task route action'],
  ['applyTalentPolicy', 'TalentPolicyService.applyPolicy', 'player:{playerId}', ['policyId'], 'non-idempotent', 'registry action'],
  ['saveTalentPolicy', 'TalentPolicyService.saveCustomPolicy', 'player:{playerId}', ['policy'], 'non-idempotent', 'registry action'],
  ['deleteTalentPolicy', 'TalentPolicyService.deleteCustomPolicy', 'player:{playerId}', ['policyId'], 'non-idempotent', 'registry action'],
  ['setArmyFormation', 'MilitaryService.setArmyFormation', 'player:{playerId}', ['cityId', 'slot'], 'non-idempotent', 'registry action'],
  ['veteranCampWithdraw', 'MilitaryService.veteranCampWithdraw', 'player:{playerId}', ['cityId'], 'non-idempotent', 'registry action'],
  ['veteranCampUpgrade', 'MilitaryService.veteranCampUpgrade', 'player:{playerId}', ['cityId'], 'non-idempotent', 'registry action'],
  ['research', 'TechTreeService.research', 'player:{playerId}', ['techId'], 'non-idempotent', 'frontend local canResearch debt'],
  ['seekFamousPerson', 'FamousPersonService.seekFamousPerson', 'player:{playerId}', ['source'], 'non-idempotent', 'candidate/cooldown domain debt remains server authority'],
  ['acceptFamousPerson', 'FamousPersonService.acceptFamousPerson', 'player:{playerId}', ['candidateId'], 'non-idempotent', 'candidate availability must not be a client command blocker'],
  ['dismissFamousPersonCandidate', 'FamousPersonService.dismissFamousPersonCandidate', 'player:{playerId}', ['candidateId'], 'non-idempotent', 'registry action'],
  ['assignFamousAttributePoint', 'FamousPersonService.assignAttributePoint', 'player:{playerId}', ['personId', 'attribute'], 'non-idempotent', 'registry action'],
  ['startConquest', 'TerritoryAction.execute', 'territory:{territoryId}', ['territoryId'], 'non-idempotent', 'shared territory owner; missing id blocks owner resolution'],
  ['claimConquest', 'TerritoryAction.execute', 'territory:{territoryId}', ['territoryId'], 'non-idempotent', 'shared territory owner; missing id blocks owner resolution'],
  ['resolveCapture', 'TerritoryAction.execute', 'player:{playerId}', ['decisionId'], 'non-idempotent', 'current capture decision private unless made shared later'],
  ['renameCity', 'TerritoryAction.execute', 'player:{playerId}', ['territoryId', 'name'], 'non-idempotent', 'city naming currently private unless shared naming is introduced'],
  ['renamePolity', 'TerritoryAction.execute', 'player:{playerId}', ['name'], 'non-idempotent', 'registry action'],
  ['switchCity', 'TerritoryAction.execute', 'player:{playerId}', ['cityId'], 'non-idempotent', 'registry action'],
  ['startWorldMarch', 'TerritoryAction.execute', 'player:{playerId}', ['targetQ', 'targetR', 'formationSlot'], 'non-idempotent', 'may hand off to encounter owner when contesting shared encounter'],
  ['returnWorldMarch', 'TerritoryAction.execute', 'player:{playerId}', ['missionId'], 'non-idempotent', 'registry action'],
  ['stopWorldMarch', 'TerritoryAction.execute', 'player:{playerId}', ['missionId'], 'non-idempotent', 'registry action'],
  ['startWorldCombat', 'WorldCombatSessionService.openSession', 'encounter:{encounterId}', ['encounterId', 'combatEncounterId', 'missionId', 'targetQ', 'targetR'], 'non-idempotent', 'bypasses registry; owner lookup blocker until encounter id is explicit before domain execution'],
  ['resolveWorldCombat', 'WorldCombatSessionService.resolveSession', 'encounter:{encounterId}', ['encounterId', 'combatEncounterId', 'battleId'], 'non-idempotent', 'bypasses registry; battle/session id must resolve encounter before domain execution'],
]);

const GAME_ACTIONS = Object.freeze(GAME_ACTION_ROWS.map(
  ([action, handler, provisionalOwnerKey, targetIdFields, idempotencyClassification, notes]) => ({
    action,
    commandType: action,
    handler,
    routeEntry: action === 'claimTaskReward'
      ? 'server:game-tasks-claim'
      : (['startWorldCombat', 'resolveWorldCombat'].includes(action)
        ? 'server:game-action-world-combat-bypass'
        : 'server:game-action-registry'),
    provisionalOwnerKey,
    targetIdFields,
    idempotencyClassification,
    migrationPhase: provisionalOwnerKey.startsWith('territory:') || provisionalOwnerKey.startsWith('encounter:')
      ? 'shared-owner-staging'
      : 'pipeline-pending',
    contracts: ['COP-ENTRY-001', 'COP-OWNER-001', 'COP-IDEMP-001'],
    notes,
  }),
));

const FRONTEND_HELPER_ROWS = Object.freeze([
  ['reportClientEvent', '/client-events', 'clientEventIngest', ['type', 'requestId'], 'diagnostic-non-idempotent'],
  ['uploadClientOperationLog', '/client-operation-logs', 'clientOperationLogIngest', ['requestId', 'entries'], 'diagnostic-non-idempotent'],
  ['build', '/game/action', 'build', ['buildingId'], 'server-fallback-id'],
  ['upgrade', '/game/action', 'upgrade', ['buildingId'], 'non-idempotent'],
  ['assignJob', '/game/action', 'assign', ['job', 'count'], 'non-idempotent'],
  ['applyTalentPolicy', '/game/action', 'applyTalentPolicy', ['policyId', 'policy'], 'non-idempotent'],
  ['saveTalentPolicy', '/game/action', 'saveTalentPolicy', ['policy'], 'non-idempotent'],
  ['deleteTalentPolicy', '/game/action', 'deleteTalentPolicy', ['policyId'], 'non-idempotent'],
  ['research', '/game/action', 'research', ['techId'], 'non-idempotent'],
  ['seekFamousPerson', '/game/action', 'seekFamousPerson', ['source'], 'non-idempotent'],
  ['acceptFamousPerson', '/game/action', 'acceptFamousPerson', ['candidateId'], 'non-idempotent'],
  ['dismissFamousPersonCandidate', '/game/action', 'dismissFamousPersonCandidate', ['candidateId'], 'non-idempotent'],
  ['assignFamousAttributePoint', '/game/action', 'assignFamousAttributePoint', ['personId', 'attribute'], 'non-idempotent'],
  ['setArmyFormation', '/game/action', 'setArmyFormation', ['cityId', 'slot'], 'non-idempotent'],
  ['veteranCampWithdraw', '/game/action', 'veteranCampWithdraw', ['cityId', 'soldiers'], 'non-idempotent'],
  ['veteranCampUpgrade', '/game/action', 'veteranCampUpgrade', ['cityId'], 'non-idempotent'],
  ['advanceEra', '/game/action', 'advanceEra', [], 'non-idempotent'],
  ['claimTaskReward', '/game/tasks/claim', 'claimTaskReward', ['taskId', 'category'], 'non-idempotent'],
  ['claimEvent', '/game/action', 'claimEvent', ['eventId', 'optionId'], 'non-idempotent'],
  ['resolveCapture', '/game/action', 'resolveCapture', ['decisionId', 'choice'], 'non-idempotent'],
  ['startWorldMarch', '/game/action', 'startWorldMarch', ['targetQ', 'targetR', 'formationSlot'], 'non-idempotent'],
  ['returnWorldMarch', '/game/action', 'returnWorldMarch', ['missionId'], 'non-idempotent'],
  ['stopWorldMarch', '/game/action', 'stopWorldMarch', ['missionId'], 'non-idempotent'],
  ['startWorldCombat', '/game/action', 'startWorldCombat', ['missionId', 'formationSlot', 'targetQ', 'targetR'], 'non-idempotent'],
  ['resolveWorldCombat', '/game/action', 'resolveWorldCombat', ['battleId', 'inputStream'], 'non-idempotent'],
  ['startConquest', '/game/action', 'startConquest', ['territoryId'], 'non-idempotent'],
  ['claimConquest', '/game/action', 'claimConquest', ['territoryId'], 'non-idempotent'],
  ['renameCity', '/game/action', 'renameCity', ['territoryId', 'name'], 'non-idempotent'],
  ['renamePolity', '/game/action', 'renamePolity', ['name'], 'non-idempotent'],
  ['switchCity', '/game/action', 'switchCity', ['cityId'], 'non-idempotent'],
  ['advanceTutorial', '/game/action', 'tutorialAdvance', ['step'], 'non-idempotent'],
  ['heartbeat', '/game/heartbeat', 'heartbeatMarchSettlement|worldMarchClientReportIngest', ['worldMarchClientReport'], 'non-idempotent'],
]);

const FRONTEND_WRITE_HELPERS = Object.freeze(FRONTEND_HELPER_ROWS.map(
  ([helper, endpoint, commandType, payloadSource, idempotencyClassification]) => ({
    helper,
    endpoint,
    commandType,
    payloadSource,
    submissionClassification: 'legacy-direct-gameapi',
    commandIdSupport: helper === 'build' ? 'clientCommand only for build via attachClientCommand' : 'none',
    idempotencyClassification,
    domainDisplayCanSuppressCall: ['advanceEra', 'research', 'startWorldMarch', 'claimConquest', 'acceptFamousPerson'].includes(helper),
    contracts: ['COP-ENTRY-001', 'COP-CLIENT-002', 'COP-ENVELOPE-001', 'COP-IDEMP-001'],
    evidence: ['frontend/js/api/GameAPI.js'],
  }),
));

const FRONTEND_DIRECT_SUBMIT_CALL_SITE_ROWS = Object.freeze([
  ['frontend:direct-submit:frontend-js-controllers-BuildingController-js:17:build', 'frontend/js/controllers/BuildingController.js', 17, 'build', 'build', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-BuildingController-js:17:upgrade', 'frontend/js/controllers/BuildingController.js', 17, 'upgrade', 'upgrade', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-CaptureController-js:57:resolveCapture', 'frontend/js/controllers/CaptureController.js', 57, 'resolveCapture', 'resolveCapture', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-EventController-js:44:claimEvent', 'frontend/js/controllers/EventController.js', 44, 'claimEvent', 'claimEvent', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:233:startConquest', 'frontend/js/controllers/TerritoryController.js', 233, 'startConquest', 'startConquest', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:246:startConquest', 'frontend/js/controllers/TerritoryController.js', 246, 'startConquest', 'startConquest', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:256:claimConquest', 'frontend/js/controllers/TerritoryController.js', 256, 'claimConquest', 'claimConquest', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:260:claimConquest', 'frontend/js/controllers/TerritoryController.js', 260, 'claimConquest', 'claimConquest', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:265:switchCity', 'frontend/js/controllers/TerritoryController.js', 265, 'switchCity', 'switchCity', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-platform-ArmyFormationEditorController-js:298:setArmyFormation', 'frontend/js/platform/ArmyFormationEditorController.js', 298, 'setArmyFormation', 'setArmyFormation', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1170:switchCity', 'frontend/js/platform/CanvasActionController.js', 1170, 'switchCity', 'switchCity', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1265:assignJob', 'frontend/js/platform/CanvasActionController.js', 1265, 'assignJob', 'assign', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1316:upgrade', 'frontend/js/platform/CanvasActionController.js', 1316, 'upgrade', 'upgrade', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1317:build', 'frontend/js/platform/CanvasActionController.js', 1317, 'build', 'build', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1332:advanceEra', 'frontend/js/platform/CanvasActionController.js', 1332, 'advanceEra', 'advanceEra', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1342:research', 'frontend/js/platform/CanvasActionController.js', 1342, 'research', 'research', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1408:resolveCapture', 'frontend/js/platform/CanvasActionController.js', 1408, 'resolveCapture', 'resolveCapture', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1435:claimEvent', 'frontend/js/platform/CanvasActionController.js', 1435, 'claimEvent', 'claimEvent', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1522:seekFamousPerson', 'frontend/js/platform/CanvasActionController.js', 1522, 'seekFamousPerson', 'seekFamousPerson', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1535:acceptFamousPerson', 'frontend/js/platform/CanvasActionController.js', 1535, 'acceptFamousPerson', 'acceptFamousPerson', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1545:dismissFamousPersonCandidate', 'frontend/js/platform/CanvasActionController.js', 1545, 'dismissFamousPersonCandidate', 'dismissFamousPersonCandidate', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1555:assignFamousAttributePoint', 'frontend/js/platform/CanvasActionController.js', 1555, 'assignFamousAttributePoint', 'assignFamousAttributePoint', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:2032:claimConquest', 'frontend/js/platform/CanvasActionController.js', 2032, 'claimConquest', 'claimConquest', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:2177:startConquest', 'frontend/js/platform/CanvasActionController.js', 2177, 'startConquest', 'startConquest', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:2192:startConquest', 'frontend/js/platform/CanvasActionController.js', 2192, 'startConquest', 'startConquest', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:2209:claimConquest', 'frontend/js/platform/CanvasActionController.js', 2209, 'claimConquest', 'claimConquest', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:814:veteranCampWithdraw', 'frontend/js/platform/CanvasActionController.js', 814, 'veteranCampWithdraw', 'veteranCampWithdraw', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:824:veteranCampUpgrade', 'frontend/js/platform/CanvasActionController.js', 824, 'veteranCampUpgrade', 'veteranCampUpgrade', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:1299:heartbeat', 'frontend/js/platform/CanvasGameApp.js', 1299, 'heartbeat', 'heartbeat', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2491:startWorldCombat', 'frontend/js/platform/CanvasGameApp.js', 2491, 'startWorldCombat', 'startWorldCombat', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2517:resolveWorldCombat', 'frontend/js/platform/CanvasGameApp.js', 2517, 'resolveWorldCombat', 'resolveWorldCombat', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2600:seekFamousPerson', 'frontend/js/platform/CanvasGameApp.js', 2600, 'seekFamousPerson', 'seekFamousPerson', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2614:acceptFamousPerson', 'frontend/js/platform/CanvasGameApp.js', 2614, 'acceptFamousPerson', 'acceptFamousPerson', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2628:dismissFamousPersonCandidate', 'frontend/js/platform/CanvasGameApp.js', 2628, 'dismissFamousPersonCandidate', 'dismissFamousPersonCandidate', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2642:assignFamousAttributePoint', 'frontend/js/platform/CanvasGameApp.js', 2642, 'assignFamousAttributePoint', 'assignFamousAttributePoint', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2776:assignJob', 'frontend/js/platform/CanvasGameApp.js', 2776, 'assignJob', 'assign', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2801:applyTalentPolicy', 'frontend/js/platform/CanvasGameApp.js', 2801, 'applyTalentPolicy', 'applyTalentPolicy', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2824:advanceEra', 'frontend/js/platform/CanvasGameApp.js', 2824, 'advanceEra', 'advanceEra', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2860:startWorldMarch', 'frontend/js/platform/CanvasGameApp.js', 2860, 'startWorldMarch', 'startWorldMarch', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2905:returnWorldMarch', 'frontend/js/platform/CanvasGameApp.js', 2905, 'returnWorldMarch', 'returnWorldMarch', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2936:stopWorldMarch', 'frontend/js/platform/CanvasGameApp.js', 2936, 'stopWorldMarch', 'stopWorldMarch', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2965:claimTaskReward', 'frontend/js/platform/CanvasGameApp.js', 2965, 'claimTaskReward', 'claimTaskReward', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:3006:switchCity', 'frontend/js/platform/CanvasGameApp.js', 3006, 'switchCity', 'switchCity', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:3182:renamePolity', 'frontend/js/platform/CanvasGameApp.js', 3182, 'renamePolity', 'renamePolity', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:3183:renameCity', 'frontend/js/platform/CanvasGameApp.js', 3183, 'renameCity', 'renameCity', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-GameCommandService-js:127:upgrade', 'frontend/js/platform/GameCommandService.js', 127, 'upgrade', 'upgrade', 'compatibility-direct-submit', 'ClientCommandSender game-command service adapter'],
  ['frontend:direct-submit:frontend-js-platform-GameCommandService-js:128:build', 'frontend/js/platform/GameCommandService.js', 128, 'build', 'build', 'compatibility-direct-submit', 'ClientCommandSender game-command service adapter'],
  ['frontend:direct-submit:frontend-js-platform-GameCommandService-js:143:research', 'frontend/js/platform/GameCommandService.js', 143, 'research', 'research', 'compatibility-direct-submit', 'ClientCommandSender game-command service adapter'],
  ['frontend:direct-submit:frontend-js-platform-GameCommandService-js:173:switchCity', 'frontend/js/platform/GameCommandService.js', 173, 'switchCity', 'switchCity', 'compatibility-direct-submit', 'ClientCommandSender game-command service adapter'],
  ['frontend:direct-submit:frontend-js-platform-WorldMarchActionHandler-js:502:startWorldMarch', 'frontend/js/platform/WorldMarchActionHandler.js', 502, 'startWorldMarch', 'startWorldMarch', 'controller-direct-submit', 'ClientCommandSender world-march adapter'],
  ['frontend:direct-submit:frontend-js-platform-WorldMarchActionHandler-js:524:returnWorldMarch', 'frontend/js/platform/WorldMarchActionHandler.js', 524, 'returnWorldMarch', 'returnWorldMarch', 'controller-direct-submit', 'ClientCommandSender world-march adapter'],
  ['frontend:direct-submit:frontend-js-platform-WorldMarchActionHandler-js:545:stopWorldMarch', 'frontend/js/platform/WorldMarchActionHandler.js', 545, 'stopWorldMarch', 'stopWorldMarch', 'controller-direct-submit', 'ClientCommandSender world-march adapter'],
  ['frontend:direct-submit:frontend-js-services-GameStateSync-js:151:heartbeat', 'frontend/js/services/GameStateSync.js', 151, 'heartbeat', 'heartbeat', 'compatibility-direct-submit', 'ClientCommandSender service bridge'],
  ['frontend:direct-submit:frontend-js-tutorial-TutorialGuideController-js:154:advanceTutorial', 'frontend/js/tutorial/TutorialGuideController.js', 154, 'advanceTutorial', 'tutorialAdvance', 'controller-direct-submit', 'ClientCommandSender tutorial adapter'],
]);

const FRONTEND_DIRECT_SUBMIT_COMMAND_PATHS = Object.freeze(FRONTEND_DIRECT_SUBMIT_CALL_SITE_ROWS.map(
  ([inventoryId, pathName, line, helper, commandType, submissionClassification, migrationTarget]) => ({
    inventoryId,
    path: pathName,
    line,
    callSiteKey: `${pathName}:${line}:${helper}`,
    classification: 'command-submit',
    submissionClassification,
    producer: `${pathName}:${line}`,
    consumer: `GameAPI.${helper}`,
    commandTypes: [commandType],
    helper,
    domainDisplayCanSuppressCall: true,
    migrationTarget,
    contracts: ['COP-ENTRY-001', 'COP-CLIENT-002', 'COP-ENVELOPE-001', 'COP-IDEMP-001'],
    evidence: [`${pathName}:${line}`],
    notes: 'Generated from the Step1 direct-submit scanner and verified by callSiteKey drift detection.',
  }),
));

const FRONTEND_COMMAND_PATHS = Object.freeze([
  {
    inventoryId: 'frontend:gameapi-write-helpers',
    path: 'frontend/js/api/GameAPI.js',
    classification: 'command-submit',
    submissionClassification: 'legacy-direct-gameapi',
    producer: 'GameAPI helper methods',
    consumer: 'GameAPI.request',
    commandTypes: FRONTEND_WRITE_HELPERS.map((helper) => helper.commandType),
    domainDisplayCanSuppressCall: true,
    contracts: ['COP-ENTRY-001', 'COP-CLIENT-002', 'COP-ENVELOPE-001', 'COP-IDEMP-001'],
    notes: 'Only build gets clientCommand metadata; all helpers remain direct request wrappers for Step1 evidence.',
  },
  {
    inventoryId: 'frontend:canvas-action-dispatcher-disabled-drop',
    path: 'frontend/js/platform/CanvasActionDispatcher.js',
    classification: 'domain-blocker',
    submissionClassification: 'compatibility-direct-submit',
    producer: 'renderer/presenter action.disabled',
    consumer: 'CanvasActionDispatcher.handle',
    commandTypes: ['advanceEra', 'research', 'claimConquest', 'startWorldMarch', 'panel actions'],
    domainDisplayCanSuppressCall: true,
    contracts: ['COP-CLIENT-001', 'COP-CLIENT-002', 'COP-ALLOWLIST-001'],
    notes: 'Dispatcher returns before dispatch when action.disabled is truthy.',
  },
  {
    inventoryId: 'frontend:canvas-panel-action-runner-disabled-drop',
    path: 'frontend/js/platform/CanvasPanelActionRunner.js',
    classification: 'domain-blocker',
    submissionClassification: 'panel-direct-submit',
    producer: 'panel descriptor action.disabled',
    consumer: 'CanvasPanelActionRunner.run',
    commandTypes: ['seekFamousPerson', 'acceptFamousPerson', 'claimTaskReward', 'formation actions'],
    domainDisplayCanSuppressCall: true,
    contracts: ['COP-CLIENT-001', 'COP-CLIENT-002', 'COP-ALLOWLIST-001'],
    notes: 'Panel runner returns true before descriptor execution when action.disabled is truthy.',
  },
  {
    inventoryId: 'frontend:canvas-game-app-advance-era-local-block',
    path: 'frontend/js/platform/CanvasGameApp.js',
    classification: 'domain-blocker',
    submissionClassification: 'controller-direct-submit',
    producer: 'CanvasGameApp.canAdvanceEraNow',
    consumer: 'CanvasGameApp.advanceEra',
    commandTypes: ['advanceEra'],
    domainDisplayCanSuppressCall: true,
    contracts: ['COP-CLIENT-001', 'COP-AUTHORITY-001', 'COP-TIME-001'],
    notes: 'advanceEra returns false before GameAPI.advanceEra when local era/tutorial/resource eligibility fails.',
  },
  ...FRONTEND_DIRECT_SUBMIT_COMMAND_PATHS,
  {
    inventoryId: 'frontend:renderers-and-presenters-intent-sources',
    path: 'frontend/js/platform/renderers and frontend/js/state/presenters',
    classification: 'intent-only',
    submissionClassification: 'renderer-intent-only',
    producer: 'civilization, tech, building, famous, territory, world march renderers/presenters',
    consumer: 'CanvasActionDispatcher/CanvasPanelActionRunner',
    commandTypes: ['advanceEra', 'research', 'build', 'acceptFamousPerson', 'claimConquest', 'startWorldMarch'],
    domainDisplayCanSuppressCall: true,
    contracts: ['COP-CLIENT-001', 'COP-CLIENT-002'],
    notes: 'Renderers/presenters should remain intent-only, but disabled/can*/ready values are unsafe if dispatch consumes them.',
  },
]);

const CLIENT_LOCAL_BLOCKS = Object.freeze([
  ['frontend:canvas-action-dispatcher-disabled-drop', 'disabled', 'domain-blocker', 'action.disabled', 'CanvasActionDispatcher.handle', 'domain-or-unknown disabled flag', 'COP-CLIENT-001'],
  ['frontend:canvas-panel-action-runner-disabled-drop', 'disabled', 'domain-blocker', 'action.disabled', 'CanvasPanelActionRunner.run', 'domain-or-unknown disabled flag', 'COP-CLIENT-001'],
  ['frontend:canvas-game-app-advance-era-local-block', 'canAdvanceEraNow', 'domain-blocker', 'canAdvanceEraNow()', 'CanvasGameApp.advanceEra', 'era/tutorial/resource eligibility', 'COP-AUTHORITY-001'],
  ['frontend:tech-research-local-canresearch', 'canResearch', 'domain-blocker', 'canResearch/local tech availability', 'research action hit targets', 'tech availability/prerequisite/points', 'COP-CLIENT-001'],
  ['frontend:building-local-cost-disabled', 'cost/unlocked/maxLevel', 'domain-blocker', 'building button disabled state', 'build/upgrade dispatch', 'resources/unlock/max level', 'COP-CLIENT-001'],
  ['frontend:famous-candidate-availability', 'candidate availability', 'domain-blocker', 'candidate/panel availability', 'accept/dismiss famous actions', 'candidate availability', 'COP-CLIENT-001'],
  ['frontend:territory-mission-ready', 'claimable/ready', 'domain-blocker', 'mission readiness presenter state', 'claimConquest dispatch', 'territory mission readiness', 'COP-OWNER-002'],
  ['frontend:world-march-passability', 'passability/busy', 'domain-blocker', 'passability and formation busy state', 'startWorldMarch dispatch', 'march route/formation eligibility', 'COP-TIME-001'],
  ['frontend:payload-target-id-missing', 'missing target id', 'transport-guard', 'missing targetId/techId/territoryId', 'command envelope construction', 'PAYLOAD_SHAPE', 'COP-CLIENT-001'],
  ['frontend:in-flight-command-key', 'in-flight', 'transport-guard', 'same command key in flight', 'future sender only', 'IN_FLIGHT', 'COP-CLIENT-001'],
]).map(([inventoryId, signal, classification, producer, consumer, reason, contract]) => ({
  inventoryId,
  signal,
  classification,
  producer,
  consumer,
  reason,
  allowedReason: classification === 'transport-guard' ? reason : '',
  forbiddenAsAllowedReason: classification === 'domain-blocker',
  contracts: [contract],
}));

const ROUTE_ORCHESTRATION_DEBT = Object.freeze([
  ['server:game-action-registry', 'load/tutorial/validate/execute/save/project/revision-retry', 'backend/routes/gameRoutes.js'],
  ['server:game-action-build-handler', 'route special-cases build and handler owns lock/load/save/project', 'backend/routes/gameRoutes.js'],
  ['server:game-tasks-claim', 'claim route owns load/execute/save/project/revision-retry', 'backend/routes/gameRoutes.js'],
  ['server:game-heartbeat-march-settlement', 'heartbeat route owns runtime settlement save', 'backend/routes/gameRoutes.js'],
  ['server:game-heartbeat-client-report', 'heartbeat route owns diagnostic report save', 'backend/routes/gameRoutes.js'],
  ['server:buildings-build-legacy-route', 'legacy route owns build/save/project', 'backend/routes/buildingRoutes.js'],
  ['server:player-login', 'login route owns lock/retry/save callback/projection', 'backend/routes/playerRoutes.js'],
  ['server:player-reset', 'reset route owns lock/save/reset/projection', 'backend/routes/playerRoutes.js'],
  ['admin:config-release-publish', 'admin route delegates app-state write to service, not gameplay pipeline', 'backend/routes/adminRoutes.js'],
  ['admin:config-release-rollback', 'admin route delegates app-state write to service, not gameplay pipeline', 'backend/routes/adminRoutes.js'],
]).map(([inventoryId, orchestration, file]) => ({
  inventoryId,
  orchestration,
  file,
  classification: 'legacy-route-orchestration-visible',
  contracts: ['COP-ROUTE-001', 'COP-ENTRY-001', 'COP-PROJECTION-001'],
}));

const HANDLER_LOCK_PERSISTENCE_DEBT = Object.freeze([
  {
    inventoryId: 'handler:BuildBuildingCommandHandler',
    file: 'backend/application/commands/BuildBuildingCommandHandler.js',
    handler: 'BuildBuildingCommandHandler.execute',
    lockOwner: 'repository.withPlayerStateLock',
    persistenceOwner: 'repository.save',
    helperMediated: false,
    classification: 'legacy-handler-lock-save-visible',
    contracts: ['COP-HANDLER-001', 'COP-LOCK-001', 'COP-CONCURRENCY-001'],
    notes: 'Step1 reports this as debt; it does not claim handler migration.',
  },
  {
    inventoryId: 'handler:world-combat-session-services',
    file: 'backend/services/worldCombat',
    handler: 'WorldCombatSessionService/WorldCombatEncounterService',
    lockOwner: 'none shared-owner abstraction',
    persistenceOwner: 'WorldEncounterRepository.upsertEncounter',
    helperMediated: true,
    classification: 'shared-handler-persistence-visible',
    contracts: ['COP-HANDLER-001', 'COP-SHARED-001', 'COP-LOCK-001'],
    notes: 'Shared encounter persistence is visible until encounter owner lock exists.',
  },
]);

const SHARED_OWNER_LOOKUPS = Object.freeze([
  ['startConquest', 'territory:{territoryId}', ['territoryId'], ['none'], 'TerritoryService/TerritoryAction', 'OWNER_TARGET_MISSING_TERRITORY_ID', true, 'territory-id accepted; coordinate-only rejected for owner resolution'],
  ['claimConquest', 'territory:{territoryId}', ['territoryId'], ['none'], 'TerritoryService/TerritoryAction', 'OWNER_TARGET_MISSING_TERRITORY_ID', true, 'territory-id accepted; player fallback forbidden'],
  ['resolveCapture', 'player:{playerId}', ['decisionId'], ['capture decision lookup if made shared later'], 'TerritoryAction', 'OWNER_TARGET_CAPTURE_DECISION_UNRESOLVED', false, 'currently private player decision; shared capture would need explicit owner'],
  ['startWorldMarch', 'player:{playerId}|encounter:{encounterId}', ['targetQ', 'targetR', 'formationSlot'], ['coordinate to encounter lookup'], 'WorldExplorer route planning / WorldEncounterRepository', 'OWNER_TARGET_ENCOUNTER_UNRESOLVED', false, 'player-owned until contesting shared encounter; shared handoff remains blocker'],
  ['returnWorldMarch', 'player:{playerId}', ['missionId'], ['mission lookup'], 'TerritoryAction', 'OWNER_TARGET_MISSION_ID_MISSING', true, 'mission-id-only accepted for player-owned return'],
  ['stopWorldMarch', 'player:{playerId}', ['missionId'], ['mission lookup'], 'TerritoryAction', 'OWNER_TARGET_MISSION_ID_MISSING', true, 'mission-id-only accepted for player-owned stop'],
  ['startWorldCombat', 'encounter:{encounterId}', ['encounterId', 'combatEncounterId'], ['missionId', 'targetQ/targetR'], 'WorldCombatSessionService + WorldEncounterRepository', 'OWNER_TARGET_ENCOUNTER_ID_MISSING', false, 'current payload often uses mission/coords; owner lookup before domain execution is blocker'],
  ['resolveWorldCombat', 'encounter:{encounterId}', ['encounterId', 'combatEncounterId'], ['battleId -> session -> encounter'], 'WorldCombatSessionService', 'OWNER_TARGET_BATTLE_ENCOUNTER_UNRESOLVED', false, 'battle-id-only requires pre-domain session lookup'],
  ['openChest', 'loot:{chestId}', ['chestId'], ['none'], 'future loot repository', 'OWNER_TARGET_LOOT_ID_MISSING', false, 'future shared owner abstraction represented'],
  ['attackBoss', 'boss:{bossId}', ['bossId'], ['none'], 'future boss repository', 'OWNER_TARGET_BOSS_ID_MISSING', false, 'future shared owner abstraction represented'],
]).map(([commandType, ownerKeyType, requiredPayloadIdFields, fallbackLookupFields, lookupModule, missingTargetError, lookupBeforeDomainValidation, notes]) => ({
  commandType,
  ownerKeyType,
  requiredPayloadIdFields,
  fallbackLookupFields,
  lookupModule,
  missingTargetError,
  lookupBeforeDomainValidation,
  classification: lookupBeforeDomainValidation ? 'lookup-declared' : 'owner-resolution-blocker',
  contracts: ['COP-OWNER-001', 'COP-OWNER-002', 'COP-SHARED-001'],
  notes,
}));

const SHARED_OWNER_WRITES = Object.freeze([
  ['territory', ['startConquest', 'claimConquest'], 'territory:{territoryId}', 'currently route/player lock; needs shared owner lock', 'COP-SHARED-001'],
  ['encounter', ['startWorldCombat', 'resolveWorldCombat'], 'encounter:{encounterId}', 'currently player lock plus encounter repository upsert; needs shared owner lock', 'COP-SHARED-001'],
  ['world-march-handoff', ['startWorldMarch'], 'player:{playerId}|encounter:{encounterId}', 'handoff to shared encounter must be explicit before Step3', 'COP-OWNER-002'],
  ['loot', ['openChest'], 'loot:{lootId}', 'future owner abstraction represented; no current route migration', 'COP-SHARED-001'],
  ['boss', ['attackBoss'], 'boss:{bossId}', 'future owner abstraction represented; no current route migration', 'COP-SHARED-001'],
]).map(([ownerType, commandTypes, requiredOwnerModel, currentOwnerModel, contract]) => ({
  ownerType,
  commandTypes,
  requiredOwnerModel,
  currentOwnerModel,
  classification: 'shared-owner-decision-recorded',
  contracts: [contract, 'COP-OWNER-001', 'COP-LOCK-001'],
}));

const SERVER_WRITE_EXCLUSIONS = Object.freeze([
  {
    inventoryId: 'server-exclusion:player-register-disabled',
    route: '/api/player/register',
    method: 'POST',
    file: 'backend/routes/playerRoutes.js',
    line: 94,
    owner: 'auth/platform',
    reason: 'Route is an explicit 403 REGISTER_DISABLED stub and performs no repository, service, or filesystem write.',
    retirementCondition: 'Remove this exclusion before re-enabling player registration or adding any persistence to the route.',
    growthPreventionTest: 'Step1 route scanner must report POST /api/player/register if write signals are added.',
    classification: 'explicit-no-write-route-exclusion',
    contracts: ['COP-ENTRY-001', 'COP-ALLOWLIST-001'],
    evidence: ['backend/routes/playerRoutes.js:94'],
    notes: 'This is documentation of a verified no-write route, not a suppression for scanner drift.',
  },
]);

const ALLOWLIST_DEBT_RECORDS = Object.freeze([]);

module.exports = {
  ALLOWLIST_DEBT_RECORDS,
  CLIENT_LOCAL_BLOCKS,
  FRONTEND_COMMAND_PATHS,
  FRONTEND_WRITE_HELPERS,
  GAME_ACTIONS,
  HANDLER_LOCK_PERSISTENCE_DEBT,
  ROUTE_ORCHESTRATION_DEBT,
  SERVER_WRITE_ENTRIES,
  SERVER_WRITE_EXCLUSIONS,
  SHARED_OWNER_LOOKUPS,
  SHARED_OWNER_WRITES,
};
