'use strict';

function entry(data) {
  return Object.freeze({
    idempotencyClassification: 'non-idempotent',
    migrationPhase: 'pipeline-pending',
    commandEnvelopePhase: 'report-only-normalized',
    ownerResolutionPhase: 'report-only-resolved',
    ownerLockInfrastructurePhase: 'owner-lock-foundation-ready',
    idempotencyStorePhase: 'available-route-not-migrated',
    commandPipelinePhase: 'skeleton-ready-route-not-migrated',
    contracts: ['COP-ENTRY-001'],
    evidence: [],
    notes: '',
    ...data,
  });
}

const SERVER_WRITE_ENTRIES = Object.freeze([
  entry({
    inventoryId: 'server:game-action-build-handler',
    route: '/api/game/action',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'build',
    provisionalOwnerKey: 'player:{playerId}',
    targetIdFields: ['target', 'buildingId'],
    currentExecutor: 'BuildBuildingCommandHandler',
    currentLockOwner: 'CommandExecutionPipeline.withOwnerLocks',
    currentPersistenceOwner: 'CommandCommitter',
    currentProjectionOwner: 'GameCommandDefinitionFactory',
    idempotencyClassification: 'client-idempotent',
    migrationPhase: 'pipeline-migrated-phase5',
    commandEnvelopePhase: 'blocking-client-envelope',
    ownerResolutionPhase: 'blocking-resolved',
    idempotencyStorePhase: 'live',
    commandPipelinePhase: 'live',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-HANDLER-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/gameRoutes.js', 'backend/application/commands/BuildBuildingCommandHandler.js'],
    notes: 'Build is the first live pipeline command; its handler owns validation and mutation only.',
  }),
  entry({
    inventoryId: 'server:game-action-registry',
    route: '/api/game/action',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'registry-actions',
    provisionalOwnerKey: 'mixed-see-game-action-inventory',
    targetIdFields: ['action-specific'],
    currentExecutor: 'CommandExecutionPipeline -> GameActionCommandHandler -> GameActionRegistry.execute',
    currentLockOwner: 'CommandExecutionPipeline.withOwnerLocks',
    currentPersistenceOwner: 'CommandCommitter',
    currentProjectionOwner: 'GameCommandDefinitionFactory',
    idempotencyClassification: 'client-idempotent',
    migrationPhase: 'pipeline-migrated-phase6',
    commandEnvelopePhase: 'blocking-client-envelope',
    ownerResolutionPhase: 'blocking-resolved',
    idempotencyStorePhase: 'live',
    commandPipelinePhase: 'live',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-OWNER-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/gameRoutes.js', 'backend/actions/GameActionRegistry.js'],
    notes: 'Registry actions, including shared territory contests, use the live command pipeline.',
  }),
  entry({
    inventoryId: 'server:game-action-world-combat-bypass',
    route: '/api/game/action',
    method: 'POST',
    writeEntryKind: 'shared-target-write',
    commandType: 'startWorldCombat|resolveWorldCombat',
    provisionalOwnerKey: 'encounter:{encounterId}',
    targetIdFields: ['encounterId', 'combatEncounterId', 'missionId', 'battleId'],
    currentExecutor: 'CommandExecutionPipeline -> WorldCombatCommandHandler',
    currentLockOwner: 'CommandExecutionPipeline.withOwnerLocks',
    currentPersistenceOwner: 'CommandCommitter.commitCommandState',
    currentProjectionOwner: 'GameCommandDefinitionFactory',
    idempotencyClassification: 'client-idempotent',
    migrationPhase: 'pipeline-migrated-phase6',
    commandEnvelopePhase: 'blocking-client-envelope',
    ownerResolutionPhase: 'blocking-resolved',
    idempotencyStorePhase: 'live',
    commandPipelinePhase: 'live',
    contracts: ['COP-ENTRY-001', 'COP-OWNER-002', 'COP-SHARED-001', 'COP-ROUTE-001'],
    evidence: ['backend/routes/gameRoutes.js', 'backend/services/worldCombat/WorldCombatSessionService.js'],
    notes: 'World combat uses an explicit encounter id and stages shared mutations for CommandCommitter.',
  }),
  entry({
    inventoryId: 'server:game-tasks-claim',
    route: '/api/game/tasks/claim',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'claimTaskReward',
    provisionalOwnerKey: 'player:{playerId}',
    targetIdFields: ['taskId', 'category'],
    currentExecutor: 'TaskCenterService.claimTask',
    currentLockOwner: 'CommandExecutionPipeline.withOwnerLocks',
    currentPersistenceOwner: 'CommandCommitter',
    currentProjectionOwner: 'GameCommandDefinitionFactory',
    idempotencyClassification: 'client-idempotent',
    migrationPhase: 'pipeline-migrated-phase5',
    commandEnvelopePhase: 'blocking-client-envelope',
    ownerResolutionPhase: 'blocking-resolved',
    idempotencyStorePhase: 'live',
    commandPipelinePhase: 'live',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/gameRoutes.js'],
  }),
  entry({
    inventoryId: 'server:game-heartbeat-march-settlement',
    route: '/api/game/heartbeat',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'heartbeatMarchSettlement',
    provisionalOwnerKey: 'player:{playerId}',
    targetIdFields: ['active exploreMissions due time'],
    currentExecutor: 'CommandExecutionPipeline -> HeartbeatCommandHandler',
    currentLockOwner: 'CommandExecutionPipeline.withOwnerLocks',
    currentPersistenceOwner: 'CommandCommitter save-if-changed',
    currentProjectionOwner: 'GameCommandDefinitionFactory heartbeat projection',
    idempotencyClassification: 'client-idempotent',
    migrationPhase: 'pipeline-migrated-phase5',
    commandEnvelopePhase: 'blocking-client-envelope',
    ownerResolutionPhase: 'blocking-resolved',
    idempotencyStorePhase: 'live',
    commandPipelinePhase: 'live',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TIME-001'],
    evidence: ['backend/routes/gameRoutes.js'],
  }),
  entry({
    inventoryId: 'server:game-heartbeat-client-report',
    route: '/api/game/heartbeat',
    method: 'POST',
    writeEntryKind: 'diagnostic-write',
    commandType: 'worldMarchClientReportIngest',
    provisionalOwnerKey: 'diagnostic:{playerId}',
    targetIdFields: ['worldMarchClientReport.missions'],
    currentExecutor: 'CommandExecutionPipeline -> HeartbeatCommandHandler',
    currentLockOwner: 'CommandExecutionPipeline.withOwnerLocks',
    currentPersistenceOwner: 'CommandCommitter save-if-changed',
    currentProjectionOwner: 'GameCommandDefinitionFactory heartbeat projection',
    idempotencyClassification: 'client-idempotent',
    migrationPhase: 'pipeline-migrated-phase5',
    commandEnvelopePhase: 'blocking-client-envelope',
    ownerResolutionPhase: 'blocking-resolved',
    idempotencyStorePhase: 'live',
    commandPipelinePhase: 'live',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001'],
    evidence: ['backend/routes/gameRoutes.js'],
  }),
  entry({
    inventoryId: 'server:buildings-build-legacy-route',
    route: '/api/buildings/build',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'build',
    provisionalOwnerKey: 'player:{playerId}',
    targetIdFields: ['buildingType'],
    currentExecutor: 'CommandExecutionPipeline -> BuildBuildingCommandHandler',
    currentLockOwner: 'CommandExecutionPipeline.withOwnerLocks',
    currentPersistenceOwner: 'CommandCommitter',
    currentProjectionOwner: 'GameCommandDefinitionFactory',
    idempotencyClassification: 'client-idempotent',
    migrationPhase: 'pipeline-migrated-phase5',
    commandEnvelopePhase: 'blocking-client-envelope',
    ownerResolutionPhase: 'blocking-resolved',
    idempotencyStorePhase: 'live',
    commandPipelinePhase: 'live',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/buildingRoutes.js'],
  }),
  entry({
    inventoryId: 'server:player-login',
    route: '/api/player/login',
    method: 'POST',
    writeEntryKind: 'auth-player-write',
    commandType: 'playerLogin',
    provisionalOwnerKey: 'player:{username}',
    targetIdFields: ['username'],
    currentExecutor: 'authService.loginPlayer',
    currentLockOwner: 'route:withPlayerStateLock(username)',
    currentPersistenceOwner: 'route callback:repository.save',
    currentProjectionOwner: 'route:getClientGameStateFromNormalized',
    migrationPhase: 'classified-non-gameplay-command',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-LOCK-001'],
    evidence: ['backend/routes/playerRoutes.js'],
  }),
  entry({
    inventoryId: 'server:player-reset',
    route: '/api/player/reset',
    method: 'POST',
    writeEntryKind: 'player-write',
    commandType: 'playerReset',
    provisionalOwnerKey: 'player:{playerId}|territory-owner:{playerId}',
    targetIdFields: [],
    currentExecutor: 'CommandExecutionPipeline -> PlayerResetCommandHandler',
    currentLockOwner: 'CommandExecutionPipeline.withOwnerLocks',
    currentPersistenceOwner: 'CommandCommitter reset-player-state',
    currentProjectionOwner: 'GameCommandDefinitionFactory',
    idempotencyClassification: 'client-idempotent',
    migrationPhase: 'pipeline-migrated-phase5',
    commandEnvelopePhase: 'blocking-client-envelope',
    ownerResolutionPhase: 'blocking-resolved',
    idempotencyStorePhase: 'live',
    commandPipelinePhase: 'live',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-LOCK-001', 'COP-SHARED-001'],
    evidence: [
      'backend/routes/playerRoutes.js',
      'backend/application/commands/CommandOwnerResolver.js',
      'backend/repositories/GameStateRepository.js',
    ],
    notes: 'Reset locks the player stream and the player-owned territory collection before deleting shared rows.',
  }),
  entry({
    inventoryId: 'admin:ops-login-audit',
    route: '/api/admin/ops/login',
    method: 'POST',
    writeEntryKind: 'ops-audit-write',
    commandType: 'opsLoginAudit',
    provisionalOwnerKey: 'ops:global',
    targetIdFields: ['username', 'clientIp'],
    currentExecutor: 'OpsAuthService.login + OpsControlService.appendAudit',
    currentLockOwner: 'none',
    currentPersistenceOwner: 'OpsControlService.appendAudit -> fs.appendFileSync',
    currentProjectionOwner: 'route:ops login result',
    idempotencyClassification: 'audit-append-only-no-client-id',
    migrationPhase: 'classified-non-gameplay-ops-command',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/opsRoutes.js:23', 'backend/services/OpsControlService.js:237'],
    notes: 'Login success/failure/rate-limit attempts append ops audit records outside gameplay state.',
  }),
  entry({
    inventoryId: 'admin:ops-maintenance-state',
    route: '/api/admin/ops/maintenance',
    method: 'POST',
    writeEntryKind: 'ops-state-write',
    commandType: 'opsMaintenanceSet',
    provisionalOwnerKey: 'ops:global',
    targetIdFields: ['enabled', 'reason', 'message'],
    currentExecutor: 'OpsControlService.setMaintenanceState',
    currentLockOwner: 'filesystem-local',
    currentPersistenceOwner: 'writeJsonFile -> fs.writeFileSync plus OpsControlService.appendAudit',
    currentProjectionOwner: 'route:maintenance result',
    idempotencyClassification: 'last-write-wins-no-client-id',
    migrationPhase: 'classified-non-gameplay-ops-command',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/opsRoutes.js:64', 'backend/services/OpsControlService.js:64', 'backend/services/OpsControlService.js:207'],
    notes: 'Maintenance state is persisted to an ops JSON file and also appends an audit record.',
  }),
  entry({
    inventoryId: 'admin:ops-restart-audit',
    route: '/api/admin/ops/restart',
    method: 'POST',
    writeEntryKind: 'ops-audit-and-process-write',
    commandType: 'opsRestartAccepted',
    provisionalOwnerKey: 'ops:global',
    targetIdFields: ['delayMs'],
    currentExecutor: 'OpsControlService.appendAudit + OpsControlService.restartService',
    currentLockOwner: 'none',
    currentPersistenceOwner: 'OpsControlService.appendAudit -> fs.appendFileSync and pm2 process control',
    currentProjectionOwner: 'route:accepted restart result',
    idempotencyClassification: 'non-idempotent',
    migrationPhase: 'classified-non-gameplay-ops-command',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001', 'COP-TRACE-001', 'COP-IDEMP-001'],
    evidence: ['backend/routes/opsRoutes.js:71', 'backend/services/OpsControlService.js:237', 'backend/services/OpsControlService.js:514'],
    notes: 'Restart requests append accepted/failed audit records and can trigger PM2 process restart.',
  }),
  entry({
    inventoryId: 'diagnostic:client-events-ingest',
    route: '/api/client-events',
    method: 'POST',
    writeEntryKind: 'diagnostic-write',
    commandType: 'clientEventIngest',
    provisionalOwnerKey: 'diagnostic:anonymous-or-client',
    targetIdFields: ['type'],
    currentExecutor: 'ObservabilityService.recordClientEvent',
    currentLockOwner: 'none',
    currentPersistenceOwner: 'observabilityService',
    currentProjectionOwner: 'route:accepted event summary',
    migrationPhase: 'diagnostic-classified',
    contracts: ['COP-ENTRY-001', 'COP-TRACE-001'],
    evidence: ['backend/routes/clientEventsRoutes.js'],
  }),
  entry({
    inventoryId: 'diagnostic:client-operation-log-ingest',
    route: '/api/client-operation-logs',
    method: 'POST',
    writeEntryKind: 'diagnostic-write',
    commandType: 'clientOperationLogIngest',
    provisionalOwnerKey: 'diagnostic:{playerId}',
    targetIdFields: ['requestId', 'entries'],
    currentExecutor: 'logService.logClientOperationSnapshot',
    currentLockOwner: 'none',
    currentPersistenceOwner: 'logService client_operation_logs table',
    currentProjectionOwner: 'route:accepted log summary',
    migrationPhase: 'diagnostic-classified',
    contracts: ['COP-ENTRY-001', 'COP-TRACE-001', 'COP-CLIENT-001'],
    evidence: ['backend/routes/clientEventsRoutes.js', 'backend/services/logService.js'],
  }),
  entry({
    inventoryId: 'admin:config-release-publish',
    route: '/api/admin/config-releases/publish',
    method: 'POST',
    writeEntryKind: 'config-write',
    commandType: 'configReleasePublish',
    provisionalOwnerKey: 'config:gameplay',
    targetIdFields: ['release payload'],
    currentExecutor: 'ConfigReleaseService.publishRelease',
    currentLockOwner: 'service-owned-or-filesystem',
    currentPersistenceOwner: 'ConfigReleaseService',
    currentProjectionOwner: 'route:release result',
    migrationPhase: 'config-write-classified',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001'],
    evidence: ['backend/routes/adminRoutes.js'],
  }),
  entry({
    inventoryId: 'admin:config-release-rollback',
    route: '/api/admin/config-releases/rollback',
    method: 'POST',
    writeEntryKind: 'config-write',
    commandType: 'configReleaseRollback',
    provisionalOwnerKey: 'config:gameplay',
    targetIdFields: ['releaseId'],
    currentExecutor: 'ConfigReleaseService.rollbackRelease',
    currentLockOwner: 'service-owned-or-filesystem',
    currentPersistenceOwner: 'ConfigReleaseService',
    currentProjectionOwner: 'route:release result',
    migrationPhase: 'config-write-classified',
    contracts: ['COP-ENTRY-001', 'COP-ROUTE-001'],
    evidence: ['backend/routes/adminRoutes.js'],
  }),
  entry({
    inventoryId: 'worker:world-worker-runtime-writes',
    route: 'backend/world-worker.js',
    method: 'BACKGROUND',
    writeEntryKind: 'background-worker-write',
    commandType: 'worldWorkerPlayerTick|worldWorkerPersonUpdate|worldWorkerDiplomacyTick',
    provisionalOwnerKey: 'player:{playerId}|encounter:{encounterId}|world-social:global|person:{personId}|diplomacy:{pairId}',
    targetIdFields: ['playerId', 'encounterIds', 'playerIds', 'personIds', 'pairId'],
    currentExecutor: 'CommandExecutionPipeline -> WorldWorkerService command definitions',
    currentLockOwner: 'CommandExecutionPipeline.withOwnerLocks',
    currentPersistenceOwner: 'CommandCommitter.commitCommandState',
    currentProjectionOwner: 'none',
    idempotencyClassification: 'internal-idempotent',
    migrationPhase: 'pipeline-migrated-phase6',
    commandEnvelopePhase: 'blocking-internal-envelope',
    ownerResolutionPhase: 'blocking-resolved-split',
    idempotencyStorePhase: 'live',
    commandPipelinePhase: 'live',
    contracts: ['COP-ENTRY-001', 'COP-SHARED-001', 'COP-LOCK-001'],
    evidence: ['backend/world-worker.js', 'backend/services/realtime/WorldWorkerService.js'],
  }),
]);

const GAME_ACTION_ROWS = Object.freeze([
  ['build', 'BuildBuildingAction or BuildBuildingCommandHandler', 'player:{playerId}', ['target', 'buildingId'], 'server-fallback-id', 'handler special case plus legacy route debt'],
  ['upgrade', 'BuildBuildingAction', 'player:{playerId}', ['target'], 'non-idempotent', 'registry action'],
  ['advanceEra', 'AdvanceEraAction', 'player:{playerId}', [], 'non-idempotent', 'frontend local domain blocker is visible debt'],
  ['claimEvent', 'ClaimEventAction', 'player:{playerId}', ['eventId', 'optionId'], 'non-idempotent', 'event target currently private'],
  ['assign', 'AssignPopulationAction', 'player:{playerId}', ['target', 'count'], 'non-idempotent', 'registry action'],
  ['tutorialAdvance', 'TutorialService.advanceClientStep', 'player:{playerId}', ['step'], 'non-idempotent', 'registry action'],
  ['claimTaskReward', 'TaskCenterService.claimTask', 'player:{playerId}', ['taskId', 'category'], 'non-idempotent', 'task route action'],
  ['applyTalentPolicy', 'TalentPolicyService.applyPolicy', 'player:{playerId}', ['policyId'], 'non-idempotent', 'registry action'],
  ['saveTalentPolicy', 'TalentPolicyService.saveCustomPolicy', 'player:{playerId}', ['policy'], 'non-idempotent', 'registry action'],
  ['deleteTalentPolicy', 'TalentPolicyService.deleteCustomPolicy', 'player:{playerId}', ['policyId'], 'non-idempotent', 'registry action'],
  ['setArmyFormation', 'MilitaryService.setArmyFormation', 'player:{playerId}', ['cityId', 'slot'], 'non-idempotent', 'registry action'],
  ['veteranCampWithdraw', 'MilitaryService.veteranCampWithdraw', 'player:{playerId}', ['cityId'], 'non-idempotent', 'registry action'],
  ['veteranCampUpgrade', 'MilitaryService.veteranCampUpgrade', 'player:{playerId}', ['cityId'], 'non-idempotent', 'registry action'],
  ['research', 'TechTreeService.research', 'player:{playerId}', ['techId'], 'non-idempotent', 'frontend local canResearch debt'],
  ['seekFamousPerson', 'FamousPersonService.seekFamousPerson', 'player:{playerId}', ['source'], 'non-idempotent', 'candidate/cooldown domain debt remains server authority'],
  ['acceptFamousPerson', 'FamousPersonService.acceptFamousPerson', 'player:{playerId}', ['candidateId'], 'non-idempotent', 'candidate availability must not be a client command blocker'],
  ['dismissFamousPersonCandidate', 'FamousPersonService.dismissFamousPersonCandidate', 'player:{playerId}', ['candidateId'], 'non-idempotent', 'registry action'],
  ['assignFamousAttributePoint', 'FamousPersonService.assignAttributePoint', 'player:{playerId}', ['personId', 'attribute'], 'non-idempotent', 'registry action'],
  ['startConquest', 'TerritoryAction.execute', 'territory:{territoryId}', ['territoryId'], 'non-idempotent', 'shared territory owner; missing id blocks owner resolution'],
  ['claimConquest', 'TerritoryAction.execute', 'territory:{territoryId}', ['territoryId'], 'non-idempotent', 'shared territory owner; missing id blocks owner resolution'],
  ['resolveCapture', 'TerritoryAction.execute', 'player:{playerId}', ['decisionId'], 'non-idempotent', 'current capture decision private unless made shared later'],
  ['renameCity', 'TerritoryAction.execute', 'territory:{territoryId}', ['territoryId', 'name'], 'non-idempotent', 'shared city naming locks the canonical territory row'],
  ['renamePolity', 'TerritoryAction.execute', 'player:{playerId}', ['name'], 'non-idempotent', 'registry action'],
  ['switchCity', 'TerritoryAction.execute', 'player:{playerId}', ['cityId'], 'non-idempotent', 'registry action'],
  ['startWorldMarch', 'TerritoryAction.execute', 'player:{playerId}', ['targetQ', 'targetR', 'formationSlot'], 'non-idempotent', 'may hand off to encounter owner when contesting shared encounter'],
  ['returnWorldMarch', 'TerritoryAction.execute', 'player:{playerId}', ['missionId'], 'non-idempotent', 'registry action'],
  ['stopWorldMarch', 'TerritoryAction.execute', 'player:{playerId}', ['missionId'], 'non-idempotent', 'registry action'],
  ['startWorldCombat', 'WorldCombatCommandHandler', 'encounter:{encounterId}', ['encounterId', 'combatEncounterId', 'missionId', 'targetQ', 'targetR'], 'non-idempotent', 'explicit encounter id is required before owner locking'],
  ['resolveWorldCombat', 'WorldCombatCommandHandler', 'encounter:{encounterId}', ['encounterId', 'combatEncounterId', 'battleId'], 'non-idempotent', 'explicit encounter id must match the persisted battle session'],
]);

const PHASE6_SHARED_GAME_ACTIONS = new Set([
  'startConquest',
  'claimConquest',
  'renameCity',
  'startWorldCombat',
  'resolveWorldCombat',
]);
const PHASE6_DEFERRED_GAME_ACTIONS = new Set();

const GAME_ACTIONS = Object.freeze(GAME_ACTION_ROWS.map(
  ([action, handler, provisionalOwnerKey, targetIdFields, idempotencyClassification, notes]) => ({
    action,
    commandType: action,
    handler,
    routeEntry: action === 'build'
      ? 'server:game-action-build-handler'
      : (action === 'claimTaskReward'
      ? 'server:game-tasks-claim'
      : (['startWorldCombat', 'resolveWorldCombat'].includes(action)
        ? 'server:game-action-world-combat-bypass'
        : 'server:game-action-registry')),
    provisionalOwnerKey,
    targetIdFields,
    legacyIdempotencyClassification: idempotencyClassification,
    idempotencyClassification: PHASE6_DEFERRED_GAME_ACTIONS.has(action)
      ? 'client-envelope-server-idempotency-pending'
      : 'client-idempotent',
    commandEnvelopePhase: PHASE6_DEFERRED_GAME_ACTIONS.has(action)
      ? 'report-only-phase6-deferred'
      : 'blocking-client-envelope',
    ownerResolutionPhase: PHASE6_DEFERRED_GAME_ACTIONS.has(action)
      ? (['startWorldCombat', 'resolveWorldCombat'].includes(action)
        ? 'report-only-blocked'
        : 'report-only-resolved-phase6-deferred')
      : 'blocking-resolved',
    idempotencyStorePhase: PHASE6_DEFERRED_GAME_ACTIONS.has(action) ? 'phase6-pending' : 'live',
    commandPipelinePhase: PHASE6_DEFERRED_GAME_ACTIONS.has(action) ? 'phase6-pending' : 'live',
    migrationPhase: PHASE6_SHARED_GAME_ACTIONS.has(action)
      ? 'pipeline-migrated-phase6'
      : 'pipeline-migrated-phase5',
    contracts: ['COP-ENTRY-001', 'COP-OWNER-001', 'COP-IDEMP-001'],
    notes,
  }),
));

const FRONTEND_HELPER_ROWS = Object.freeze([
  ['reportClientEvent', '/client-events', 'clientEventIngest', ['type', 'requestId'], 'client-idempotent'],
  ['uploadClientOperationLog', '/client-operation-logs', 'clientOperationLogIngest', ['requestId', 'entries'], 'client-idempotent'],
  ['build', '/game/action', 'build', ['buildingId'], 'client-idempotent'],
  ['upgrade', '/game/action', 'upgrade', ['buildingId'], 'client-idempotent'],
  ['assignJob', '/game/action', 'assign', ['job', 'count'], 'client-idempotent'],
  ['applyTalentPolicy', '/game/action', 'applyTalentPolicy', ['policyId', 'policy'], 'client-idempotent'],
  ['saveTalentPolicy', '/game/action', 'saveTalentPolicy', ['policy'], 'client-idempotent'],
  ['deleteTalentPolicy', '/game/action', 'deleteTalentPolicy', ['policyId'], 'client-idempotent'],
  ['research', '/game/action', 'research', ['techId'], 'client-idempotent'],
  ['seekFamousPerson', '/game/action', 'seekFamousPerson', ['source'], 'client-idempotent'],
  ['acceptFamousPerson', '/game/action', 'acceptFamousPerson', ['candidateId'], 'client-idempotent'],
  ['dismissFamousPersonCandidate', '/game/action', 'dismissFamousPersonCandidate', ['candidateId'], 'client-idempotent'],
  ['assignFamousAttributePoint', '/game/action', 'assignFamousAttributePoint', ['personId', 'attribute'], 'client-idempotent'],
  ['setArmyFormation', '/game/action', 'setArmyFormation', ['cityId', 'slot'], 'client-idempotent'],
  ['veteranCampWithdraw', '/game/action', 'veteranCampWithdraw', ['cityId', 'soldiers'], 'client-idempotent'],
  ['veteranCampUpgrade', '/game/action', 'veteranCampUpgrade', ['cityId'], 'client-idempotent'],
  ['advanceEra', '/game/action', 'advanceEra', [], 'client-idempotent'],
  ['resetPlayer', '/player/reset', 'playerReset', [], 'client-idempotent'],
  ['claimTaskReward', '/game/tasks/claim', 'claimTaskReward', ['taskId', 'category'], 'client-idempotent'],
  ['claimEvent', '/game/action', 'claimEvent', ['eventId', 'optionId'], 'client-idempotent'],
  ['resolveCapture', '/game/action', 'resolveCapture', ['decisionId', 'choice'], 'client-idempotent'],
  ['startWorldMarch', '/game/action', 'startWorldMarch', ['targetQ', 'targetR', 'formationSlot'], 'client-idempotent'],
  ['returnWorldMarch', '/game/action', 'returnWorldMarch', ['missionId'], 'client-idempotent'],
  ['stopWorldMarch', '/game/action', 'stopWorldMarch', ['missionId'], 'client-idempotent'],
  ['startWorldCombat', '/game/action', 'startWorldCombat', ['missionId', 'formationSlot', 'targetQ', 'targetR'], 'client-idempotent'],
  ['resolveWorldCombat', '/game/action', 'resolveWorldCombat', ['battleId', 'inputStream'], 'client-idempotent'],
  ['startConquest', '/game/action', 'startConquest', ['territoryId'], 'client-idempotent'],
  ['claimConquest', '/game/action', 'claimConquest', ['territoryId'], 'client-idempotent'],
  ['renameCity', '/game/action', 'renameCity', ['territoryId', 'name'], 'client-idempotent'],
  ['renamePolity', '/game/action', 'renamePolity', ['name'], 'client-idempotent'],
  ['switchCity', '/game/action', 'switchCity', ['cityId'], 'client-idempotent'],
  ['advanceTutorial', '/game/action', 'tutorialAdvance', ['step'], 'client-idempotent'],
  ['heartbeat', '/game/heartbeat', 'heartbeatMarchSettlement|worldMarchClientReportIngest', ['worldMarchClientReport'], 'client-idempotent'],
]);

const FRONTEND_WRITE_HELPERS = Object.freeze(FRONTEND_HELPER_ROWS.map(
  ([helper, endpoint, commandType, payloadSource, idempotencyClassification]) => ({
    helper,
    endpoint,
    commandType,
    payloadSource,
    submissionClassification: 'through-client-command-sender',
    commandIdSupport: 'stable client commandId and idempotencyKey via ClientCommandSender',
    idempotencyClassification,
    domainDisplayCanSuppressCall: false,
    contracts: ['COP-ENTRY-001', 'COP-CLIENT-002', 'COP-ENVELOPE-001', 'COP-IDEMP-001'],
    evidence: ['frontend/js/api/ClientCommandSender.js', 'frontend/js/api/GameAPI.js'],
  }),
));

const FRONTEND_DIRECT_SUBMIT_CALL_SITE_ROWS = Object.freeze([
  ['frontend:direct-submit:frontend-auth-js:208:resetPlayer', 'frontend/auth.js', 208, 'resetPlayer', 'playerReset', 'auth-controller-submit', 'ClientCommandSender via GameAPI.resetPlayer'],
  ['frontend:direct-submit:frontend-js-controllers-BuildingController-js:17:build', 'frontend/js/controllers/BuildingController.js', 17, 'build', 'build', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-BuildingController-js:17:upgrade', 'frontend/js/controllers/BuildingController.js', 17, 'upgrade', 'upgrade', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-CaptureController-js:57:resolveCapture', 'frontend/js/controllers/CaptureController.js', 57, 'resolveCapture', 'resolveCapture', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-EventController-js:44:claimEvent', 'frontend/js/controllers/EventController.js', 44, 'claimEvent', 'claimEvent', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:239:startConquest', 'frontend/js/controllers/TerritoryController.js', 239, 'startConquest', 'startConquest', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:252:startConquest', 'frontend/js/controllers/TerritoryController.js', 252, 'startConquest', 'startConquest', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:262:claimConquest', 'frontend/js/controllers/TerritoryController.js', 262, 'claimConquest', 'claimConquest', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:266:claimConquest', 'frontend/js/controllers/TerritoryController.js', 266, 'claimConquest', 'claimConquest', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-controllers-TerritoryController-js:271:switchCity', 'frontend/js/controllers/TerritoryController.js', 271, 'switchCity', 'switchCity', 'controller-direct-submit', 'ClientCommandSender via controller action adapter'],
  ['frontend:direct-submit:frontend-js-platform-ArmyFormationEditorController-js:304:setArmyFormation', 'frontend/js/platform/ArmyFormationEditorController.js', 304, 'setArmyFormation', 'setArmyFormation', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1186:switchCity', 'frontend/js/platform/CanvasActionController.js', 1186, 'switchCity', 'switchCity', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1279:assignJob', 'frontend/js/platform/CanvasActionController.js', 1279, 'assignJob', 'assign', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1292:advanceEra', 'frontend/js/platform/CanvasActionController.js', 1292, 'advanceEra', 'advanceEra', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1302:research', 'frontend/js/platform/CanvasActionController.js', 1302, 'research', 'research', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1368:resolveCapture', 'frontend/js/platform/CanvasActionController.js', 1368, 'resolveCapture', 'resolveCapture', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1394:claimEvent', 'frontend/js/platform/CanvasActionController.js', 1394, 'claimEvent', 'claimEvent', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1480:seekFamousPerson', 'frontend/js/platform/CanvasActionController.js', 1480, 'seekFamousPerson', 'seekFamousPerson', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1493:acceptFamousPerson', 'frontend/js/platform/CanvasActionController.js', 1493, 'acceptFamousPerson', 'acceptFamousPerson', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1503:dismissFamousPersonCandidate', 'frontend/js/platform/CanvasActionController.js', 1503, 'dismissFamousPersonCandidate', 'dismissFamousPersonCandidate', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1513:assignFamousAttributePoint', 'frontend/js/platform/CanvasActionController.js', 1513, 'assignFamousAttributePoint', 'assignFamousAttributePoint', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:1974:claimConquest', 'frontend/js/platform/CanvasActionController.js', 1974, 'claimConquest', 'claimConquest', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:2119:startConquest', 'frontend/js/platform/CanvasActionController.js', 2119, 'startConquest', 'startConquest', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:2134:startConquest', 'frontend/js/platform/CanvasActionController.js', 2134, 'startConquest', 'startConquest', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:2151:claimConquest', 'frontend/js/platform/CanvasActionController.js', 2151, 'claimConquest', 'claimConquest', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:842:veteranCampWithdraw', 'frontend/js/platform/CanvasActionController.js', 842, 'veteranCampWithdraw', 'veteranCampWithdraw', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasActionController-js:851:veteranCampUpgrade', 'frontend/js/platform/CanvasActionController.js', 851, 'veteranCampUpgrade', 'veteranCampUpgrade', 'controller-direct-submit', 'ClientCommandSender frontend command adapter'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:1322:heartbeat', 'frontend/js/platform/CanvasGameApp.js', 1322, 'heartbeat', 'heartbeat', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2507:startWorldCombat', 'frontend/js/platform/CanvasGameApp.js', 2507, 'startWorldCombat', 'startWorldCombat', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2539:resolveWorldCombat', 'frontend/js/platform/CanvasGameApp.js', 2539, 'resolveWorldCombat', 'resolveWorldCombat', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2626:seekFamousPerson', 'frontend/js/platform/CanvasGameApp.js', 2626, 'seekFamousPerson', 'seekFamousPerson', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2640:acceptFamousPerson', 'frontend/js/platform/CanvasGameApp.js', 2640, 'acceptFamousPerson', 'acceptFamousPerson', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2654:dismissFamousPersonCandidate', 'frontend/js/platform/CanvasGameApp.js', 2654, 'dismissFamousPersonCandidate', 'dismissFamousPersonCandidate', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2668:assignFamousAttributePoint', 'frontend/js/platform/CanvasGameApp.js', 2668, 'assignFamousAttributePoint', 'assignFamousAttributePoint', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2789:assignJob', 'frontend/js/platform/CanvasGameApp.js', 2789, 'assignJob', 'assign', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2814:applyTalentPolicy', 'frontend/js/platform/CanvasGameApp.js', 2814, 'applyTalentPolicy', 'applyTalentPolicy', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2828:advanceEra', 'frontend/js/platform/CanvasGameApp.js', 2828, 'advanceEra', 'advanceEra', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2864:startWorldMarch', 'frontend/js/platform/CanvasGameApp.js', 2864, 'startWorldMarch', 'startWorldMarch', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2909:returnWorldMarch', 'frontend/js/platform/CanvasGameApp.js', 2909, 'returnWorldMarch', 'returnWorldMarch', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2940:stopWorldMarch', 'frontend/js/platform/CanvasGameApp.js', 2940, 'stopWorldMarch', 'stopWorldMarch', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:2969:claimTaskReward', 'frontend/js/platform/CanvasGameApp.js', 2969, 'claimTaskReward', 'claimTaskReward', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:3010:switchCity', 'frontend/js/platform/CanvasGameApp.js', 3010, 'switchCity', 'switchCity', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:3171:renamePolity', 'frontend/js/platform/CanvasGameApp.js', 3171, 'renamePolity', 'renamePolity', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-CanvasGameApp-js:3172:renameCity', 'frontend/js/platform/CanvasGameApp.js', 3172, 'renameCity', 'renameCity', 'compatibility-direct-submit', 'ClientCommandSender CanvasGameApp facade'],
  ['frontend:direct-submit:frontend-js-platform-GameCommandService-js:125:upgrade', 'frontend/js/platform/GameCommandService.js', 125, 'upgrade', 'upgrade', 'compatibility-direct-submit', 'ClientCommandSender game-command service adapter'],
  ['frontend:direct-submit:frontend-js-platform-GameCommandService-js:126:build', 'frontend/js/platform/GameCommandService.js', 126, 'build', 'build', 'compatibility-direct-submit', 'ClientCommandSender game-command service adapter'],
  ['frontend:direct-submit:frontend-js-platform-GameCommandService-js:141:research', 'frontend/js/platform/GameCommandService.js', 141, 'research', 'research', 'compatibility-direct-submit', 'ClientCommandSender game-command service adapter'],
  ['frontend:direct-submit:frontend-js-platform-GameCommandService-js:171:switchCity', 'frontend/js/platform/GameCommandService.js', 171, 'switchCity', 'switchCity', 'compatibility-direct-submit', 'ClientCommandSender game-command service adapter'],
  ['frontend:direct-submit:frontend-js-platform-WorldMarchActionHandler-js:461:startWorldMarch', 'frontend/js/platform/WorldMarchActionHandler.js', 461, 'startWorldMarch', 'startWorldMarch', 'controller-direct-submit', 'ClientCommandSender world-march adapter'],
  ['frontend:direct-submit:frontend-js-platform-WorldMarchActionHandler-js:483:returnWorldMarch', 'frontend/js/platform/WorldMarchActionHandler.js', 483, 'returnWorldMarch', 'returnWorldMarch', 'controller-direct-submit', 'ClientCommandSender world-march adapter'],
  ['frontend:direct-submit:frontend-js-platform-WorldMarchActionHandler-js:504:stopWorldMarch', 'frontend/js/platform/WorldMarchActionHandler.js', 504, 'stopWorldMarch', 'stopWorldMarch', 'controller-direct-submit', 'ClientCommandSender world-march adapter'],
  ['frontend:direct-submit:frontend-js-services-GameStateSync-js:151:heartbeat', 'frontend/js/services/GameStateSync.js', 151, 'heartbeat', 'heartbeat', 'compatibility-direct-submit', 'ClientCommandSender service bridge'],
  ['frontend:direct-submit:frontend-js-tutorial-TutorialHostContext-js:513:advanceTutorial', 'frontend/js/tutorial/TutorialHostContext.js', 513, 'advanceTutorial', 'tutorialAdvance', 'controller-direct-submit', 'ClientCommandSender tutorial adapter'],
]);

const FRONTEND_DIRECT_SUBMIT_COMMAND_PATHS = Object.freeze(FRONTEND_DIRECT_SUBMIT_CALL_SITE_ROWS.map(
  ([inventoryId, pathName, line, helper, commandType, _submissionClassification, migrationTarget]) => ({
    inventoryId,
    path: pathName,
    line,
    callSiteKey: `${pathName}:${line}:${helper}`,
    classification: 'command-submit',
    submissionClassification: 'through-client-command-sender',
    producer: `${pathName}:${line}`,
    consumer: `GameAPI.${helper}`,
    commandTypes: [commandType],
    helper,
    domainDisplayCanSuppressCall: false,
    migrationTarget,
    contracts: ['COP-ENTRY-001', 'COP-CLIENT-002', 'COP-ENVELOPE-001', 'COP-IDEMP-001'],
    evidence: [`${pathName}:${line}`],
    notes: `GameAPI.${helper} is a thin facade into ClientCommandSender; callSiteKey drift remains verified.`,
  }),
));

const FRONTEND_COMMAND_PATHS = Object.freeze([
  {
    inventoryId: 'frontend:gameapi-write-helpers',
    path: 'frontend/js/api/GameAPI.js',
    classification: 'command-submit',
    submissionClassification: 'through-client-command-sender',
    producer: 'GameAPI helper methods',
    consumer: 'ClientCommandSender.submit',
    commandTypes: FRONTEND_WRITE_HELPERS.map((helper) => helper.commandType),
    domainDisplayCanSuppressCall: false,
    contracts: ['COP-ENTRY-001', 'COP-CLIENT-002', 'COP-ENVELOPE-001', 'COP-IDEMP-001'],
    notes: 'All inventoried write helpers are thin facades into ClientCommandSender with stable command metadata.',
  },
  {
    inventoryId: 'frontend:canvas-action-dispatcher-disabled-drop',
    path: 'frontend/js/platform/CanvasActionDispatcher.js',
    classification: 'retired-step4',
    submissionClassification: 'compatibility-direct-submit',
    producer: 'renderer/presenter action.disabled visual state',
    consumer: 'CanvasActionDispatcher.handle -> ClientCommandSemantics.normalizeAction',
    commandTypes: ['advanceEra', 'research', 'claimConquest', 'startWorldMarch'],
    domainDisplayCanSuppressCall: false,
    contracts: ['COP-CLIENT-001', 'COP-CLIENT-002', 'COP-ALLOWLIST-001'],
    notes: 'Step4 retired command-submit suppression: command action disabled is converted to visualDisabled before dispatcher disabled handling.',
    retiredStep4: {
      retiredByTask: 'STEP4-T11',
      blockingGate: 'scripts/check-frontend-command-semantics.js',
      fireProbe: 'remove normalizeAction or reintroduce action.disabled command guard -> exit 1',
      date: '2026-07-10',
    },
  },
  {
    inventoryId: 'frontend:canvas-panel-action-runner-disabled-drop',
    path: 'frontend/js/platform/CanvasPanelActionRunner.js',
    classification: 'classified-ui-local',
    submissionClassification: 'panel-direct-submit',
    producer: 'panel descriptor action.disabled',
    consumer: 'CanvasPanelActionRunner.run',
    commandTypes: ['openFamousPersons', 'closeFamousPersons', 'changeFamousPersonsPage', 'panelOutsideClick'],
    domainDisplayCanSuppressCall: false,
    contracts: ['COP-CLIENT-001', 'COP-CLIENT-002', 'COP-ALLOWLIST-001'],
    notes: 'Step4 classified as UI-local: production panel descriptors only open/close/run panel UI surface actions and do not submit ClientCommandSender commands.',
    classifiedUiLocal: {
      actionType: 'openFamousPersons|closeFamousPersons|changeFamousPersonsPage|openFamousPersonDetail|closeFamousPersonDetail|showFamousSkillTooltip|clearFamousSkillTooltip|panelOutsideClick',
      reason: 'Panel actions only operate panel surface state and do not submit gameplay commands.',
      proofNotClientCommandSender: 'CanvasPanelActionRegistry built-in descriptors resolve to panel operations; production code has no CanvasPanelActionRegistry.register command-submit descriptor.',
      owner: 'frontend/platform',
      growthPreventionTest: 'scripts/check-frontend-command-semantics.test.js',
    },
  },
  {
    inventoryId: 'frontend:canvas-game-app-advance-era-local-block',
    path: 'frontend/js/platform/CanvasGameApp.js',
    classification: 'retired-step4',
    submissionClassification: 'controller-direct-submit',
    producer: 'CanvasGameApp.canAdvanceEraNow visual state',
    consumer: 'CanvasGameApp.advanceEra -> GameAPI.advanceEra',
    commandTypes: ['advanceEra'],
    domainDisplayCanSuppressCall: false,
    contracts: ['COP-CLIENT-001', 'COP-AUTHORITY-001', 'COP-TIME-001'],
    notes: 'Step4 retired local submit guard: advanceEra directly calls GameAPI.advanceEra; canAdvanceEraNow remains visual-state only.',
    retiredStep4: {
      retiredByTask: 'STEP4-T13',
      blockingGate: 'scripts/check-frontend-command-semantics.js',
      fireProbe: 'reintroduce if (!this.canAdvanceEraNow()) return false -> exit 1',
      date: '2026-07-10',
    },
  },
  ...FRONTEND_DIRECT_SUBMIT_COMMAND_PATHS,
  {
    inventoryId: 'frontend:renderers-and-presenters-intent-sources',
    path: 'frontend/js/platform/renderers and frontend/js/state/presenters',
    classification: 'intent-only',
    submissionClassification: 'renderer-intent-only',
    producer: 'civilization, tech, building, famous, territory, world march renderers/presenters',
    consumer: 'CanvasActionDispatcher/CanvasPanelActionRunner',
    commandTypes: ['advanceEra', 'research', 'build', 'acceptFamousPerson', 'claimConquest', 'startWorldMarch'],
    domainDisplayCanSuppressCall: true,
    contracts: ['COP-CLIENT-001', 'COP-CLIENT-002'],
    notes: 'Renderers/presenters should remain intent-only, but disabled/can*/ready values are unsafe if dispatch consumes them.',
  },
]);

const CLIENT_LOCAL_BLOCKS = Object.freeze([
  {
    inventoryId: 'frontend:canvas-action-dispatcher-disabled-drop',
    signal: 'disabled',
    classification: 'retired-step4',
    producer: 'action.disabled visual state',
    consumer: 'CanvasActionDispatcher.handle',
    reason: 'disabled is normalized into visualDisabled for command actions',
    allowedReason: '',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-CLIENT-001'],
    retiredStep4: {
      retiredByTask: 'STEP4-T11',
      blockingGate: 'scripts/check-frontend-command-semantics.js',
      fireProbe: 'remove normalizeAction or reintroduce action.disabled command guard -> exit 1',
      date: '2026-07-10',
    },
  },
  {
    inventoryId: 'frontend:canvas-panel-action-runner-disabled-drop',
    signal: 'disabled',
    classification: 'classified-ui-local',
    producer: 'panel descriptor action.disabled',
    consumer: 'CanvasPanelActionRunner.run',
    reason: 'panel-only UI-local disabled state',
    allowedReason: '',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-CLIENT-001'],
    classifiedUiLocal: {
      actionType: 'openFamousPersons|closeFamousPersons|changeFamousPersonsPage|openFamousPersonDetail|closeFamousPersonDetail|showFamousSkillTooltip|clearFamousSkillTooltip|panelOutsideClick',
      reason: 'Panel actions only operate panel surface state and do not submit gameplay commands.',
      proofNotClientCommandSender: 'CanvasPanelActionRegistry built-in descriptors resolve to panel operations; production code has no CanvasPanelActionRegistry.register command-submit descriptor.',
      owner: 'frontend/platform',
      growthPreventionTest: 'scripts/check-frontend-command-semantics.test.js',
    },
  },
  {
    inventoryId: 'frontend:canvas-game-app-advance-era-local-block',
    signal: 'canAdvanceEraNow',
    classification: 'retired-step4',
    producer: 'canAdvanceEraNow() visual state',
    consumer: 'CanvasGameApp.advanceEra',
    reason: 'advanceEra directly calls GameAPI.advanceEra',
    allowedReason: '',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-AUTHORITY-001'],
    retiredStep4: {
      retiredByTask: 'STEP4-T13',
      blockingGate: 'scripts/check-frontend-command-semantics.js',
      fireProbe: 'reintroduce if (!this.canAdvanceEraNow()) return false -> exit 1',
      date: '2026-07-10',
    },
  },
  {
    inventoryId: 'frontend:tech-research-local-canresearch',
    signal: 'canResearch',
    classification: 'retired-step4',
    producer: 'canResearch/local tech availability visual state',
    consumer: 'research command target',
    reason: 'research command-submit path does not consume canResearch as a blocker',
    allowedReason: '',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-CLIENT-001'],
    retiredStep4: {
      retiredByTask: 'STEP4-T14',
      blockingGate: 'scripts/check-frontend-command-semantics.js',
      fireProbe: 'add canResearch disabled command target blocker -> exit 1',
      date: '2026-07-10',
    },
  },
  {
    inventoryId: 'frontend:building-local-cost-disabled',
    signal: 'cost/unlocked/maxLevel',
    classification: 'retired-step4',
    producer: 'building button disabled visual state',
    consumer: 'build/upgrade command target',
    reason: 'build/upgrade command-submit path does not consume cost/unlocked/maxLevel as a blocker',
    allowedReason: '',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-CLIENT-001'],
    retiredStep4: {
      retiredByTask: 'STEP4-T14',
      blockingGate: 'scripts/check-frontend-command-semantics.js',
      fireProbe: 'add cost/unlocked/maxLevel disabled command target blocker -> exit 1',
      date: '2026-07-10',
    },
  },
  {
    inventoryId: 'frontend:famous-candidate-availability',
    signal: 'candidate availability',
    classification: 'retired-step4',
    producer: 'candidate/panel availability visual state',
    consumer: 'accept/dismiss famous command target',
    reason: 'famous command-submit path does not consume candidate availability as a blocker',
    allowedReason: '',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-CLIENT-001'],
    retiredStep4: {
      retiredByTask: 'STEP4-T14',
      blockingGate: 'scripts/check-frontend-command-semantics.js',
      fireProbe: 'add candidate availability command target blocker -> exit 1',
      date: '2026-07-10',
    },
  },
  {
    inventoryId: 'frontend:territory-mission-ready',
    signal: 'claimable/ready',
    classification: 'retired-step4',
    producer: 'mission readiness presenter visual state',
    consumer: 'claimConquest command target',
    reason: 'claimConquest command-submit path does not consume claimable/ready as a blocker',
    allowedReason: '',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-OWNER-002'],
    retiredStep4: {
      retiredByTask: 'STEP4-T14',
      blockingGate: 'scripts/check-frontend-command-semantics.js',
      fireProbe: 'add claimable/ready command target blocker -> exit 1',
      date: '2026-07-10',
    },
  },
  {
    inventoryId: 'frontend:world-march-passability',
    signal: 'passability/busy',
    classification: 'retired-step4',
    producer: 'passability and formation busy visual state',
    consumer: 'startWorldMarch command target',
    reason: 'startWorldMarch command-submit path does not consume passability/busy as a blocker',
    allowedReason: '',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-TIME-001'],
    retiredStep4: {
      retiredByTask: 'STEP4-T14',
      blockingGate: 'scripts/check-frontend-command-semantics.js',
      fireProbe: 'add passability/busy command target blocker -> exit 1',
      date: '2026-07-10',
    },
  },
  {
    inventoryId: 'frontend:payload-target-id-missing',
    signal: 'missing target id',
    classification: 'transport-guard',
    producer: 'missing targetId/techId/territoryId',
    consumer: 'command envelope construction',
    reason: 'PAYLOAD_SHAPE',
    allowedReason: 'PAYLOAD_SHAPE',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-CLIENT-001'],
  },
  {
    inventoryId: 'frontend:in-flight-command-key',
    signal: 'in-flight',
    classification: 'transport-guard',
    producer: 'same command key in flight',
    consumer: 'ClientCommandSender.submit',
    reason: 'IN_FLIGHT',
    allowedReason: 'IN_FLIGHT',
    forbiddenAsAllowedReason: false,
    contracts: ['COP-CLIENT-001'],
  },
]);

const ROUTE_ORCHESTRATION_DEBT = Object.freeze([
  ['server:player-login', 'login route owns lock/retry/save callback/projection', 'backend/routes/playerRoutes.js'],
  ['admin:config-release-publish', 'admin route delegates app-state write to service, not gameplay pipeline', 'backend/routes/adminRoutes.js'],
  ['admin:config-release-rollback', 'admin route delegates app-state write to service, not gameplay pipeline', 'backend/routes/adminRoutes.js'],
]).map(([inventoryId, orchestration, file]) => ({
  inventoryId,
  orchestration,
  file,
  classification: 'legacy-route-orchestration-visible',
  contracts: ['COP-ROUTE-001', 'COP-ENTRY-001', 'COP-PROJECTION-001'],
}));

const HANDLER_LOCK_PERSISTENCE_DEBT = Object.freeze([]);

const SHARED_OWNER_LOOKUPS = Object.freeze([
  ['startConquest', 'territory:{territoryId}', ['territoryId'], ['none'], 'TerritoryService/TerritoryAction', 'OWNER_TARGET_MISSING_TERRITORY_ID', true, 'territory-id accepted; coordinate-only rejected for owner resolution'],
  ['claimConquest', 'territory:{territoryId}', ['territoryId'], ['none'], 'TerritoryService/TerritoryAction', 'OWNER_TARGET_MISSING_TERRITORY_ID', true, 'territory-id accepted; player fallback forbidden'],
  ['renameCity', 'territory:{territoryId}', ['territoryId'], ['none'], 'TerritoryService/TerritoryAction', 'OWNER_TARGET_MISSING_TERRITORY_ID', true, 'shared city naming updates only while holding the territory owner'],
  ['resolveCapture', 'player:{playerId}', ['decisionId'], ['capture decision lookup if made shared later'], 'TerritoryAction', 'OWNER_TARGET_CAPTURE_DECISION_UNRESOLVED', false, 'currently private player decision; shared capture would need explicit owner'],
  ['startWorldMarch', 'player:{playerId}|encounter:{encounterId}', ['targetQ', 'targetR', 'formationSlot'], ['coordinate to encounter lookup'], 'CommandOwnerResolver / WorldEncounterRepository', 'OWNER_TARGET_ENCOUNTER_UNRESOLVED', true, 'repository lookup resolves the encounter before owner locks and hands the id to domain execution'],
  ['returnWorldMarch', 'player:{playerId}', ['missionId'], ['mission lookup'], 'TerritoryAction', 'OWNER_TARGET_MISSION_ID_MISSING', true, 'mission-id-only accepted for player-owned return'],
  ['stopWorldMarch', 'player:{playerId}', ['missionId'], ['mission lookup'], 'TerritoryAction', 'OWNER_TARGET_MISSION_ID_MISSING', true, 'mission-id-only accepted for player-owned stop'],
  ['startWorldCombat', 'encounter:{encounterId}', ['encounterId', 'combatEncounterId'], ['none'], 'WorldCombatCommandHandler + WorldEncounterRepository', 'OWNER_TARGET_ENCOUNTER_ID_MISSING', true, 'client carries the explicit encounter id and the handler verifies target coordinates'],
  ['resolveWorldCombat', 'encounter:{encounterId}', ['encounterId', 'combatEncounterId'], ['none'], 'WorldCombatCommandHandler', 'OWNER_TARGET_BATTLE_ENCOUNTER_UNRESOLVED', true, 'client carries the explicit encounter id and the handler verifies the battle session'],
  ['openChest', 'loot:{chestId}', ['chestId'], ['none'], 'future loot repository', 'OWNER_TARGET_LOOT_ID_MISSING', false, 'future shared owner abstraction represented'],
  ['attackBoss', 'boss:{bossId}', ['bossId'], ['none'], 'future boss repository', 'OWNER_TARGET_BOSS_ID_MISSING', false, 'future shared owner abstraction represented'],
]).map(([commandType, ownerKeyType, requiredPayloadIdFields, fallbackLookupFields, lookupModule, missingTargetError, lookupBeforeDomainValidation, notes]) => ({
  commandType,
  ownerKeyType,
  requiredPayloadIdFields,
  fallbackLookupFields,
  lookupModule,
  missingTargetError,
  lookupBeforeDomainValidation,
  classification: lookupBeforeDomainValidation ? 'lookup-declared' : 'owner-resolution-blocker',
  contracts: ['COP-OWNER-001', 'COP-OWNER-002', 'COP-SHARED-001'],
  notes,
}));

const SHARED_OWNER_WRITES = Object.freeze([
  ['territory', ['startConquest', 'claimConquest', 'renameCity'], 'territory:{territoryId}|territory-owner:{playerId}', 'live pipeline locks player, target territory, actor territory collection, and the current owner collection before scoped canonical persistence', 'COP-SHARED-001'],
  ['encounter', ['startWorldCombat', 'resolveWorldCombat'], 'encounter:{encounterId}', 'live pipeline stages encounter mutations and commits player plus shared state atomically', 'COP-SHARED-001'],
  ['world-march-handoff', ['startWorldMarch'], 'player:{playerId}|encounter:{encounterId}', 'repository owner lookup resolves coordinate handoff before the live pipeline acquires locks', 'COP-OWNER-002'],
  ['loot', ['openChest'], 'loot:{lootId}', 'future owner abstraction represented; no current route migration', 'COP-SHARED-001'],
  ['boss', ['attackBoss'], 'boss:{bossId}', 'future owner abstraction represented; no current route migration', 'COP-SHARED-001'],
]).map(([ownerType, commandTypes, requiredOwnerModel, currentOwnerModel, contract]) => ({
  ownerType,
  commandTypes,
  requiredOwnerModel,
  currentOwnerModel,
  classification: 'shared-owner-decision-recorded',
  contracts: [contract, 'COP-OWNER-001', 'COP-LOCK-001'],
}));

const SERVER_WRITE_EXCLUSIONS = Object.freeze([
  {
    inventoryId: 'server-exclusion:player-register-disabled',
    route: '/api/player/register',
    method: 'POST',
    file: 'backend/routes/playerRoutes.js',
    line: 94,
    owner: 'auth/platform',
    reason: 'Route is an explicit 403 REGISTER_DISABLED stub and performs no repository, service, or filesystem write.',
    retirementCondition: 'Remove this exclusion before re-enabling player registration or adding any persistence to the route.',
    growthPreventionTest: 'Step1 route scanner must report POST /api/player/register if write signals are added.',
    classification: 'explicit-no-write-route-exclusion',
    contracts: ['COP-ENTRY-001', 'COP-ALLOWLIST-001'],
    evidence: ['backend/routes/playerRoutes.js:94'],
    notes: 'This is documentation of a verified no-write route, not a suppression for scanner drift.',
  },
  {
    inventoryId: 'server-exclusion:admin-task-definitions-preview',
    route: '/api/admin/task-definitions/preview',
    method: 'POST',
    file: 'backend/routes/adminRoutes.js',
    line: 30,
    owner: 'admin/config',
    reason: 'Route builds a task-definition import preview and validation report without calling publish, save, or filesystem write APIs.',
    retirementCondition: 'Remove this exclusion before allowing task-definition preview to persist imports or write files.',
    growthPreventionTest: 'Step1 route scanner must report POST /api/admin/task-definitions/preview if write signals are added.',
    classification: 'explicit-no-write-route-exclusion',
    contracts: ['COP-ENTRY-001', 'COP-ALLOWLIST-001'],
    evidence: ['backend/routes/adminRoutes.js:30'],
    notes: 'Read-only preview documentation for a POST route that does not mutate task definitions.',
  },
  {
    inventoryId: 'server-exclusion:admin-config-releases-preview',
    route: '/api/admin/config-releases/preview',
    method: 'POST',
    file: 'backend/routes/adminRoutes.js',
    line: 76,
    owner: 'admin/config',
    reason: 'Route builds a config release candidate and comparison report without appending release history or writing the active release.',
    retirementCondition: 'Remove this exclusion before allowing config release preview to publish, rollback, append history, or write active release state.',
    growthPreventionTest: 'Step1 route scanner must report POST /api/admin/config-releases/preview if write signals are added.',
    classification: 'explicit-no-write-route-exclusion',
    contracts: ['COP-ENTRY-001', 'COP-ALLOWLIST-001'],
    evidence: ['backend/routes/adminRoutes.js:76'],
    notes: 'Read-only preview documentation for a POST route that does not mutate config release state.',
  },
]);

const ALLOWLIST_DEBT_RECORDS = Object.freeze([]);

module.exports = {
  ALLOWLIST_DEBT_RECORDS,
  CLIENT_LOCAL_BLOCKS,
  FRONTEND_COMMAND_PATHS,
  FRONTEND_WRITE_HELPERS,
  GAME_ACTIONS,
  HANDLER_LOCK_PERSISTENCE_DEBT,
  ROUTE_ORCHESTRATION_DEBT,
  SERVER_WRITE_ENTRIES,
  SERVER_WRITE_EXCLUSIONS,
  SHARED_OWNER_LOOKUPS,
  SHARED_OWNER_WRITES,
};
